import SwiftUI

/// Single-fine detail screen. Hero amount on top, status pill underneath,
/// reason + evidence in cards, action footer (Pagar / Apelar / Ver
/// apelación). Apple Sports flat — monochrome chrome, color via dot only.
struct FineDetailView: View {
    @Bindable var coordinator: FineDetailCoordinator
    var onAppeal: (() -> Void)?
    var onViewAppeal: ((Appeal) -> Void)?

    /// V1: gate for the "Anular multa" button. Resolved async on appear
    /// because governance.canPerform requires loading the user's Member row
    /// in the fine's group (cross-group fines via MyFinesView).
    let computeCanVoidFine: () async -> Bool
    /// Factory: creates a fresh `VoidFineCoordinator` each time the sheet
    /// is opened. Captures `app.governance`, repos, and `coord.refresh`
    /// (via onSubmitted) lexically in MainTabView.fineDetailScreen.
    let makeVoidFineCoordinator: () -> VoidFineCoordinator
    let currentUserId: UUID

    @State private var appealSheetPresented = false
    @State private var payConfirmPresented = false
    @State private var voidSheetPresented = false
    @State private var canVoidFine: Bool = false

    var body: some View {
        ZStack {
            Color.ruulBackgroundCanvas.ignoresSafeArea()
            ScrollView {
                VStack(alignment: .leading, spacing: RuulSpacing.s6) {
                    hero
                    reasonCard
                    evidenceSection
                    voidedSection
                    appealStatusInline
                }
                .padding(.horizontal, RuulSpacing.s5)
                .padding(.bottom, RuulSpacing.s12)
            }
            .scrollIndicators(.hidden)

            actionFooter
        }
        .navigationTitle("Multa")
        .navigationBarTitleDisplayMode(.inline)
        .task { await coordinator.refresh() }
        .task { canVoidFine = await computeCanVoidFine() }
        .ruulSheet(isPresented: $appealSheetPresented) {
            AppealFineSheet(
                isPresented: $appealSheetPresented,
                fine: coordinator.fine
            ) { reason in
                Task { await coordinator.startAppeal(reason: reason) }
            }
        }
        .ruulSheet(isPresented: $voidSheetPresented) {
            // Fresh coordinator per open: makeVoidFineCoordinator() runs each
            // time the binding flips false→true. Deliberate — avoids leaking
            // partially-filled form state from cancelled sessions. The factory
            // wires onSubmitted = { coord.refresh() } so the parent repaints
            // before the sheet dismisses.
            VoidFineSheet(
                isPresented: $voidSheetPresented,
                coordinator: makeVoidFineCoordinator()
            )
        }
    }

    // MARK: - Hero

    private var hero: some View {
        VStack(alignment: .leading, spacing: RuulSpacing.s3) {
            HStack(spacing: RuulSpacing.s2) {
                Circle()
                    .fill(statusDotColor)
                    .frame(width: 8, height: 8)
                Text(coordinator.fine.status.displayLabel)
                    .ruulTextStyle(RuulTypography.sectionLabel)
                    .foregroundStyle(Color.ruulTextPrimary)
                if coordinator.fine.status == .proposed {
                    Spacer()
                    Text("EN REVISIÓN 24H")
                        .ruulTextStyle(RuulTypography.sectionLabel)
                        .foregroundStyle(Color.ruulTextTertiary)
                }
            }
            Text(coordinator.fine.amountFormatted)
                .ruulTextStyle(RuulTypography.displayHero)
                .foregroundStyle(Color.ruulTextPrimary)
        }
        .padding(.top, RuulSpacing.s5)
    }

    // MARK: - Reason card

    private var reasonCard: some View {
        VStack(alignment: .leading, spacing: RuulSpacing.s2) {
            Text("MOTIVO")
                .ruulTextStyle(RuulTypography.sectionLabel)
                .foregroundStyle(Color.ruulTextTertiary)
            Text(coordinator.fine.reason)
                .ruulTextStyle(RuulTypography.headline)
                .foregroundStyle(Color.ruulTextPrimary)
                .fixedSize(horizontal: false, vertical: true)
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .padding(RuulSpacing.s4)
        .background(Color.ruulBackgroundElevated, in: RoundedRectangle(cornerRadius: RuulRadius.lg, style: .continuous))
        .overlay(
            RoundedRectangle(cornerRadius: RuulRadius.lg, style: .continuous)
                .stroke(Color.ruulBorderSubtle, lineWidth: 0.5)
        )
    }

    // MARK: - Evidence section (rule snapshot + details)

    @ViewBuilder
    private var evidenceSection: some View {
        if coordinator.fine.autoGenerated {
            VStack(alignment: .leading, spacing: RuulSpacing.s2) {
                Text("EVIDENCIA")
                    .ruulTextStyle(RuulTypography.sectionLabel)
                    .foregroundStyle(Color.ruulTextTertiary)
                evidenceBody
            }
        }
    }

    @ViewBuilder
    private var evidenceBody: some View {
        VStack(alignment: .leading, spacing: RuulSpacing.s2) {
            evidenceRow(label: "Generada por", value: "Regla automática")
            if let createdAt = coordinator.fine.createdAt as Date? {
                evidenceRow(label: "Fecha", value: createdAt.ruulShortDate)
            }
            if let lateMinutes = coordinator.fine.details?["minutes_late"]?.intValue {
                evidenceRow(label: "Minutos tarde", value: "\(lateMinutes)")
            }
        }
        .padding(RuulSpacing.s4)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(Color.ruulBackgroundElevated, in: RoundedRectangle(cornerRadius: RuulRadius.lg, style: .continuous))
        .overlay(
            RoundedRectangle(cornerRadius: RuulRadius.lg, style: .continuous)
                .stroke(Color.ruulBorderSubtle, lineWidth: 0.5)
        )
    }

    private func evidenceRow(label: String, value: String) -> some View {
        HStack {
            Text(label)
                .ruulTextStyle(RuulTypography.callout)
                .foregroundStyle(Color.ruulTextSecondary)
            Spacer()
            Text(value)
                .ruulTextStyle(RuulTypography.callout)
                .foregroundStyle(Color.ruulTextPrimary)
        }
    }

    // MARK: - Voided section (admin closure reason after Anular)

    @ViewBuilder
    private var voidedSection: some View {
        if coordinator.fine.status == .voided,
           let waivedReason = coordinator.fine.waivedReason,
           !waivedReason.isEmpty {
            VStack(alignment: .leading, spacing: RuulSpacing.s2) {
                Text("ANULADA POR ADMIN")
                    .ruulTextStyle(RuulTypography.sectionLabel)
                    .foregroundStyle(Color.ruulTextTertiary)
                Text(waivedReason)
                    .ruulTextStyle(RuulTypography.body)
                    .foregroundStyle(Color.ruulTextPrimary)
                    .padding(RuulSpacing.s4)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .background(
                        Color.ruulBackgroundElevated,
                        in: RoundedRectangle(cornerRadius: RuulRadius.lg, style: .continuous)
                    )
                    .overlay(
                        RoundedRectangle(cornerRadius: RuulRadius.lg, style: .continuous)
                            .stroke(Color.ruulBorderSubtle, lineWidth: 0.5)
                    )
            }
        }
    }

    // MARK: - Inline appeal status (when there's an active appeal)

    @ViewBuilder
    private var appealStatusInline: some View {
        if let appeal = coordinator.existingAppeal {
            VStack(alignment: .leading, spacing: RuulSpacing.s3) {
                HStack(spacing: RuulSpacing.s2) {
                    Circle()
                        .fill(appealDotColor(for: appeal.status))
                        .frame(width: 8, height: 8)
                    Text(appealStatusLabel(for: appeal.status))
                        .ruulTextStyle(RuulTypography.sectionLabel)
                        .foregroundStyle(Color.ruulTextPrimary)
                }
                Text(appeal.reason)
                    .ruulTextStyle(RuulTypography.body)
                    .foregroundStyle(Color.ruulTextSecondary)
                    .fixedSize(horizontal: false, vertical: true)
                if let counts = coordinator.voteCounts {
                    VoteCountsBar(counts: counts)
                }
                if appeal.isVotingOpen {
                    Button { onViewAppeal?(appeal) } label: {
                        HStack {
                            Text("Ver detalle de votación")
                                .ruulTextStyle(RuulTypography.callout)
                            Spacer()
                            Image(systemName: "arrow.right")
                                .font(.system(size: 12, weight: .bold))
                        }
                        .foregroundStyle(Color.ruulTextPrimary)
                    }
                    .buttonStyle(.plain)
                }
            }
            .padding(RuulSpacing.s4)
            .frame(maxWidth: .infinity, alignment: .leading)
            .background(Color.ruulBackgroundElevated, in: RoundedRectangle(cornerRadius: RuulRadius.lg, style: .continuous))
            .overlay(
                RoundedRectangle(cornerRadius: RuulRadius.lg, style: .continuous)
                    .stroke(Color.ruulBorderSubtle, lineWidth: 0.5)
            )
        }
    }

    // MARK: - Sticky action footer

    @ViewBuilder
    private var actionFooter: some View {
        VStack {
            Spacer()
            if coordinator.isMine {
                actionsForMyFine
            } else {
                actionsForAdmin
            }
        }
    }

    @ViewBuilder
    private var actionsForAdmin: some View {
        if canVoidFine,
           coordinator.fine.status == .proposed || coordinator.fine.status == .officialized {
            RuulButton("Anular multa", style: .destructive, size: .large, fillsWidth: true) {
                voidSheetPresented = true
            }
            .padding(.horizontal, RuulSpacing.s5)
            .padding(.vertical, RuulSpacing.s3)
            .background(.regularMaterial)
        }
    }

    @ViewBuilder
    private var actionsForMyFine: some View {
        if let appeal = coordinator.existingAppeal, appeal.isVotingOpen {
            // Already appealed — no Pagar / Apelar buttons; just keep the
            // voting status visible above. The voting itself happens in
            // VoteOnAppealView for OTHER members; the appellant just waits.
            EmptyView()
        } else {
            switch coordinator.fine.status {
            case .officialized:
                HStack(spacing: RuulSpacing.s3) {
                    RuulButton("Apelar", style: .glass, size: .large, fillsWidth: true) {
                        appealSheetPresented = true
                    }
                    RuulButton("Pagar", style: .primary, size: .large, fillsWidth: true) {
                        Task { await coordinator.payFine() }
                    }
                }
                .padding(.horizontal, RuulSpacing.s5)
                .padding(.vertical, RuulSpacing.s3)
                .background(.regularMaterial)
            case .proposed:
                Text("Esta multa se oficializa después de 24h. Si no aplica, espera a que el host la revise — o contacta directo.")
                    .ruulTextStyle(RuulTypography.caption)
                    .foregroundStyle(Color.ruulTextTertiary)
                    .multilineTextAlignment(.center)
                    .padding(.horizontal, RuulSpacing.s5)
                    .padding(.vertical, RuulSpacing.s3)
                    .frame(maxWidth: .infinity)
                    .background(.regularMaterial)
            case .paid, .voided, .inAppeal:
                EmptyView()
            }
        }
    }

    // MARK: - Helpers

    private var statusDotColor: Color {
        switch coordinator.fine.status {
        case .proposed:     return .ruulSemanticWarning
        case .officialized: return .ruulSemanticError
        case .paid:         return .ruulSemanticSuccess
        case .voided:       return .ruulTextTertiary
        case .inAppeal:     return .ruulSemanticInfo
        }
    }

    private func appealDotColor(for status: AppealStatus) -> Color {
        switch status {
        case .voting:           return .ruulSemanticInfo
        case .resolvedInFavor:  return .ruulSemanticSuccess
        case .resolvedAgainst:  return .ruulSemanticError
        case .expired:          return .ruulTextTertiary
        }
    }

    private func appealStatusLabel(for status: AppealStatus) -> String {
        switch status {
        case .voting:           return "EN VOTACIÓN"
        case .resolvedInFavor:  return "APELACIÓN GANADA"
        case .resolvedAgainst:  return "APELACIÓN PERDIDA"
        case .expired:          return "VOTACIÓN VENCIDA"
        }
    }
}
