import Foundation

/// A monetary fine — the only ConsequenceType implemented in V1.
/// Lives in the legacy `public.fines` table (see migration 00001 + 00016).
/// Sprint 1a's edge-fn rule engine inserts these with status=.proposed; the
/// 24h grace period (managed by `fine_review_periods`) auto-officializes
/// via `finalize-fine-reviews` cron unless the host calls `officialize_fine`
/// or `void_fine` first.
public struct Fine: Identifiable, Sendable, Hashable, Codable {
    public let id: UUID
    public let groupId: UUID
    public let userId: UUID            // auth.users.id (NOT group_members.id)
    public let ruleId: UUID?
    public let eventId: UUID?
    public let reason: String
    public let amount: Decimal
    public let status: FineStatus
    public let paid: Bool
    public let paidAt: Date?
    public let waived: Bool
    public let waivedAt: Date?
    public let waivedReason: String?
    public let autoGenerated: Bool
    public let issuedBy: UUID?
    public let details: JSONConfig?
    public let ruleSnapshot: JSONConfig?
    public let createdAt: Date
    public let updatedAt: Date

    public var amountFormatted: String {
        let nf = NumberFormatter()
        nf.numberStyle = .currency
        nf.currencyCode = "MXN"
        nf.maximumFractionDigits = 0
        return nf.string(from: amount as NSDecimalNumber) ?? "$\(amount)"
    }

    enum CodingKeys: String, CodingKey {
        case id
        case groupId       = "group_id"
        case userId        = "user_id"
        case ruleId        = "rule_id"
        case eventId       = "event_id"
        case reason
        case amount
        case status
        case paid
        case paidAt        = "paid_at"
        case waived
        case waivedAt      = "waived_at"
        case waivedReason  = "waived_reason"
        case autoGenerated = "auto_generated"
        case issuedBy      = "issued_by"
        case details
        case ruleSnapshot  = "rule_snapshot"
        case createdAt     = "created_at"
        case updatedAt     = "updated_at"
    }
}

public enum FineStatus: String, Codable, Sendable, Hashable, CaseIterable {
    /// Auto-generated by the rule engine. Lives in 24h grace, host can edit
    /// or void; auto-officializes after expiry via finalize-fine-reviews cron.
    case proposed     = "proposed"
    /// Past grace period or host-approved. The fined user owes this amount.
    case officialized = "officialized"
    /// User has paid (paid=true).
    case paid         = "paid"
    /// Annulled — either via successful appeal vote or admin void_fine RPC.
    case voided       = "voided"
    /// Active appeal in progress; voting hasn't closed yet.
    case inAppeal     = "in_appeal"

    public var displayLabel: String {
        switch self {
        case .proposed:     return "PROPUESTA"
        case .officialized: return "PENDIENTE"
        case .paid:         return "PAGADA"
        case .voided:       return "ANULADA"
        case .inAppeal:     return "EN APELACIÓN"
        }
    }
}
