import SwiftUI
import RuulUI
import RuulCore
import CoreLocation

// MARK: - Phase E: EventDetailHost rewired to UniversalResourceDetailView

/// Shell view that owns every piece of event-specific state needed to
/// render the polymorphic `UniversalResourceDetailView` for an event:
///
///   - `EventDetailCoordinator` — domain state + mutations, exposed as
///     `EventInteractor` to capability sections via SwiftUI environment.
///   - Sheet bindings (Share / QR / Cancel / Remind / Close / Manual fine
///     / Ledger / Rules / Member detail) so the sections call presenter
///     closures and the sheets present at this layer.
///   - Async loads: capability set from `public.resource_capabilities`,
///     governance check for manual-fine authorization.
///
/// The wider app shell (MainTabView) only has to pass in the `Event`,
/// the parent `Group`, a snapshot of the member directory, and a handful
/// of route-tear-down callbacks. Everything else is handled here. Phase
/// 11 deletes the legacy `EventDetailView` once this is the sole entry.
public struct EventDetailHost: View {
    @Environment(AppState.self) private var app

    public let event: Event
    public let group: RuulCore.Group
    public let currentUserId: UUID
    public let memberDirectory: [UUID: MemberWithProfile]
    public let calendarService: CalendarExportService?
    public let onClose: () -> Void
    public let onEditEvent: (Event) -> Void
    public let onScannerOpen: (EventDetailCoordinator) -> Void

    /// Optional sheet to auto-present once the coordinator finishes
    /// bootstrap. Used by post-create intents that want to land the
    /// user directly on an actionable surface (e.g. "Invitar gente"
    /// → .share to share the join link). Consumed exactly once on
    /// first appear so navigating back + forward doesn't re-trigger.
    public let initialSheet: Sheet?

    /// When true, auto-launches the QR scanner once the coordinator
    /// finishes bootstrap. Scanner needs the live coordinator (passed
    /// via onScannerOpen) and lives on its own RootShellState slot —
    /// can't be driven by the generic `Sheet` enum. Consumed exactly
    /// once like `initialSheet`.
    public let autoOpenScanner: Bool

    public init(
        event: Event,
        group: RuulCore.Group,
        currentUserId: UUID,
        memberDirectory: [UUID: MemberWithProfile],
        calendarService: CalendarExportService?,
        onClose: @escaping () -> Void,
        onEditEvent: @escaping (Event) -> Void,
        onScannerOpen: @escaping (EventDetailCoordinator) -> Void,
        initialSheet: Sheet? = nil,
        autoOpenScanner: Bool = false
    ) {
        self.event = event
        self.group = group
        self.currentUserId = currentUserId
        self.memberDirectory = memberDirectory
        self.calendarService = calendarService
        self.onClose = onClose
        self.onEditEvent = onEditEvent
        self.onScannerOpen = onScannerOpen
        self.initialSheet = initialSheet
        self.autoOpenScanner = autoOpenScanner
    }

    // MARK: - State

    @State private var coordinator: EventDetailCoordinator?
    @State private var enabledCapabilities: Set<String> = []
    @State private var canIssueManualFine: Bool = false
    @State private var attentionActions: [UserAction] = []
    @State private var attendeeRoute: MemberWithProfile?
    @State private var ledgerCoordinator: ResourceLedgerCoordinator?
    @State private var rulesCoordinator: ResourceRulesCoordinator?
    @State private var manualFineCoordinator: AddManualFineCoordinator?

    // Phase E: block-tree state updated whenever the underlying entities mutate
    @State private var blocks: ResourceBlocks?
    @State private var rotationConfig: RotationSnapshotInput?
    /// Recurrence pretty-label ("Recurrente · Semanal", "Recurrente ·
    /// Ciclo 4") derived from the underlying `ResourceSeries.pattern`
    /// when the event was generated by a series. nil for one-off events.
    @State private var recurrenceLabel: String?

    // Phase E: deep management sheets driven by openDestinationId routes
    @State private var showRotationParticipants: Bool = false
    @State private var showLocationEditor: Bool = false
    /// "Ver más" tap on the Activity layer opens the full
    /// `ResourceActivityHistorySheet` (wider window than the inline 5
    /// entries).
    @State private var showActivityHistory: Bool = false

    // One @State enum so individual bools don't pollute the storage map.
    @State private var sheet: Sheet?

    /// Guard so `initialSheet` only fires once per Host lifecycle —
    /// otherwise re-renders after the user dismisses the sheet would
    /// re-trigger it.
    @State private var didFireInitialSheet: Bool = false

    public enum Sheet: Identifiable, Hashable {
        case share, qr, cancelEvent, cancelAttendance, remindAttendees, closeEvent, manualFine
        // Money UX Consolidation PR-D (2026-05-24): replace the legacy
        // `.ledger` (which mounted AddLedgerEntryDestination) with a
        // picker + three canonical form sheets. `.ledger` stays as an
        // alias that redirects to `.movementPicker` for back-compat
        // with callers that haven't migrated.
        case ledger, movementPicker, movementContribute, movementExpense, movementSettle
        case rules, attendees
        public var id: Self { self }
    }

    // MARK: - Body

    public var body: some View {
        NavigationStack {
            if let coordinator {
                hosted(coordinator: coordinator)
            } else {
                bootView
            }
        }
        .task {
            guard coordinator == nil else { return }
            let bootstrap = EventDetailBootstrap(
                app: app,
                event: event,
                group: group,
                currentUserId: currentUserId,
                memberDirectory: memberDirectory
            )
            let result = await bootstrap.run()
            coordinator = result.coordinator
            enabledCapabilities = result.enabledCapabilities
            attentionActions = result.attentionActions
            canIssueManualFine = result.canIssueManualFine

            // Fire the requested initial presentation once the
            // coordinator is ready. For the scanner we use the
            // dedicated onScannerOpen callback (the scanner has its
            // own state path on RootShellState — it can't be driven
            // by the generic Sheet enum). For everything else the
            // Sheet enum drives the local sheet binding.
            if !didFireInitialSheet {
                didFireInitialSheet = true
                if autoOpenScanner, let coordinator {
                    onScannerOpen(coordinator)
                } else if let pending = initialSheet {
                    sheet = pending
                }
            }
        }
    }

    private var bootView: some View {
        ZStack {
            Color.ruulBackgroundCanvas.ignoresSafeArea()
            ProgressView()
                .controlSize(.large)
                .frame(maxWidth: .infinity, maxHeight: .infinity)
        }
    }

    @ViewBuilder
    private func hosted(coordinator: EventDetailCoordinator) -> some View {
        Group {
            if blocks != nil {
                ResourceDetailContent(
                    config: enrich(
                        .event(
                            makeEventInput(coordinator: coordinator),
                            onInvite: { sheet = .share },
                            onEdit:   { onEditEvent(coordinator.event) },
                            onRotateHost: { showRotationParticipants = true },
                            onSeeAllAttendees: { sheet = .attendees },
                            onRSVPConfirm: { Task { await coordinator.setRSVP(.going) } },
                            onRSVPCancel: { sheet = .cancelAttendance },
                            onAddToCalendar: { addToCalendarViaPresenter() },
                            toolbarMenu: makeToolbarMenu(coordinator: coordinator),
                            // SharedMoney Phase 4: render the universal
                            // Money Block under sections. Reads
                            // resource_money_view filtered to this
                            // event's id; CTAs open the group-scoped
                            // sheets pre-filled with sourceResource.
                            moneyContext: MoneyContext(
                                groupId: group.id,
                                resourceId: coordinator.event.id,
                                resourceName: coordinator.event.title,
                                currency: group.currency,
                                members: Array(memberDirectory.values),
                                onDidChange: { Task { await coordinator.refresh() } }
                            )
                        ),
                        creatorName: creatorDisplayName(for: coordinator.event)
                    )
                )
            } else {
                bootView
            }
        }
        .ruulSheetToolbar(coordinator.event.title, onClose: onClose)
        .environment(\.eventInteractor, coordinator)
        .environment(\.eventDetailPresenter, presenter)
        .task { await coordinator.refresh() }
        .task { await coordinator.startRealtime() }
        .task { await rebuildBlocks(coordinator: coordinator) }
        .onDisappear { coordinator.stopRealtime() }
        .onChange(of: coordinator.event) { _, _ in Task { await rebuildBlocks(coordinator: coordinator) } }
        .onChange(of: coordinator.myRSVP) { _, _ in Task { await rebuildBlocks(coordinator: coordinator) } }
        .eventDetailSheets(EventDetailSheets.Bindings(
            coordinator: coordinator,
            group: group,
            currentUserId: currentUserId,
            memberDirectory: memberDirectory,
            calendarService: calendarService,
            sheet: $sheet,
            attendeeRoute: $attendeeRoute,
            manualFineCoordinator: manualFineCoordinator,
            ledgerCoordinator: ledgerCoordinator,
            rulesCoordinator: rulesCoordinator
        ))
        .onChange(of: sheet) { _, newValue in
            Task { await prepareCoordinator(for: newValue) }
        }
        // Phase E deep management sheets routed via openDestinationId.
        // onSaved → `refreshAndRebuild` (refetch event row before
        // rebuilding blocks) so post-save data lands in the View even
        // when the mutation touched the underlying event row directly
        // (location → resources.metadata.location_*; the coordinator's
        // local Event snapshot is otherwise stale until next .refresh).
        .sheet(isPresented: $showRotationParticipants) {
            RotationParticipantsSheet(eventId: coordinator.event.id) {
                Task { await refreshAndRebuild(coordinator: coordinator) }
            }
            .environment(app)
            .presentationBackground(.regularMaterial)
            .presentationDragIndicator(.visible)
        }
        .sheet(isPresented: $showLocationEditor) {
            LocationEditorSheet(
                eventId: coordinator.event.id,
                initialLocationName: coordinator.event.locationName,
                viewerIsEventHost: coordinator.viewerIsHost,
                onSaved: { Task { await refreshAndRebuild(coordinator: coordinator) } }
            )
            .environment(app)
            .presentationBackground(.regularMaterial)
            .presentationDragIndicator(.visible)
        }
        .sheet(isPresented: $showActivityHistory) {
            ResourceActivityHistorySheet(
                groupId: group.id,
                resourceId: coordinator.event.id,
                displayName: coordinator.event.title
            )
            .environment(app)
            .presentationBackground(.regularMaterial)
            .presentationDragIndicator(.visible)
        }
    }

    // MARK: - Phase E: Block building

    /// Refetches the coordinator (event row + RSVPs) and rebuilds the
    /// block tree. Use this after any mutation that touches the event
    /// itself (location, edit, host change) so the View reflects the
    /// new server state instead of a stale local snapshot.
    @MainActor
    private func refreshAndRebuild(coordinator: EventDetailCoordinator) async {
        await coordinator.refresh()
        await rebuildBlocks(coordinator: coordinator)
    }

    /// Assembles an EventDetailSnapshot from the current coordinator state
    /// and runs EventBlockBuilder to produce fresh ResourceBlocks.
    @MainActor
    private func rebuildBlocks(coordinator: EventDetailCoordinator) async {
        // Load rotation config if the event belongs to a series. Also
        // derive the recurrence label from the series pattern so the
        // identity ribbon shows "Recurrente · Semanal / Quincenal /
        // Mensual" (or just "Recurrente · Ciclo N" when we can't decode
        // the cadence).
        if let seriesId = coordinator.event.seriesId {
            if let series = try? await app.resourceSeriesRepo.fetchById(seriesId) {
                rotationConfig = RotationSnapshotInput.from(series: series)
                recurrenceLabel = Self.makeRecurrenceLabel(
                    series: series,
                    cycleNumber: coordinator.event.cycleNumber
                )
            } else {
                rotationConfig = nil
                recurrenceLabel = "Recurrente"
            }
        } else {
            rotationConfig = nil
            recurrenceLabel = nil
        }

        let snapshot = EventDetailSnapshot(
            event: coordinator.event,
            myRSVP: coordinator.myRSVP,
            rotationConfig: rotationConfig,
            cycleNumber: coordinator.event.cycleNumber,
            memberDirectory: memberDirectory,
            viewerIsHost: coordinator.viewerIsHost
        )

        let viewerCtx = BlockViewerContext(
            userId: currentUserId,
            permissions: viewerPermissions,
            activeModules: Set(group.effectiveActiveModules),
            memberId: memberDirectory[currentUserId]?.member.id
        )

        let built = EventBlockBuilder().build(
            source: snapshot,
            viewer: viewerCtx,
            now: Date()
        )

        // Phase E activity feed wiring (post-build augmentation) — uses
        // the shared ActivityFeedLoader so every host renders the same
        // shape and the limit+1 trick reports `hasMoreActivity` honestly.
        let feed = await ActivityFeedLoader.load(
            app: app,
            groupId: group.id,
            resourceId: coordinator.event.id
        )
        blocks = ResourceBlocks(
            identity: built.identity,
            state: built.state,
            properties: built.properties,
            capabilities: built.capabilities,
            relations: built.relations,
            activityHead: feed.entries,
            hasMoreActivity: feed.hasMore
        )
    }

    /// Permissions the viewer holds in this group (for BlockViewerContext).
    private var viewerPermissions: Set<Permission> {
        guard let me = memberDirectory[currentUserId]?.member else { return [] }
        let catalog = group.effectiveRoles
        var perms = Set<Permission>()
        for raw in me.rawRoles {
            if let def = catalog[raw] {
                for p in def.permissions { perms.insert(p) }
            }
        }
        return perms
    }

    // MARK: - Phase E: Primary action dispatch

    @MainActor
    private func dispatchPrimary(blocks: ResourceBlocks, coordinator: EventDetailCoordinator) async {
        guard let kind = blocks.state.primaryAction?.kind else { return }
        switch kind {
        case .rsvpConfirm:
            await coordinator.setRSVP(.going, plusOnes: 0, reason: nil)
        case .rsvpCancel:
            sheet = .cancelAttendance
        case .viewHostActions:
            // Reserved for a future host-actions menu (recordar / cerrar
            // / cancelar / reabrir). EventBlockBuilder doesn't emit this
            // kind today — when it does, replace this with a real menu
            // sheet instead of routing to .closeEvent (which is only one
            // of those actions and was misleading).
            break
        case .none,
             .exerciseRight, .openContribute, .openBooking,
             .viewClosed, .payFine, .castVote:
            break  // not applicable for events
        }
    }

    // MARK: - Phase E: Block open-destination routing

    private func openDestination(_ id: String, coordinator: EventDetailCoordinator) {
        switch id {
        case "rotation.participants":
            showRotationParticipants = true
        case "location.editor":
            showLocationEditor = true
        case "rsvp.manager":
            sheet = .attendees
        case "event.activity":
            sheet = .attendees  // route to attendees/activity list
        default:
            break
        }
    }

    private func openRelation(_ card: RelationCard) {
        // Phase 2: resource_links deep navigation
    }

    // MARK: - Legacy Context wiring (kept for eventDetailSheets modifier compatibility)

    private var presenter: EventDetailPresenter {
        EventDetailPresenter(
            onPresentShareSheet: { sheet = .share },
            onPresentMemberQR: { sheet = .qr },
            onAddToWallet: { Task { _ = await coordinator?.generateWalletPass() } },
            onAddToCalendar: addToCalendarViaPresenter,
            onPresentScanner: {
                if let coordinator { onScannerOpen(coordinator) }
            },
            onPresentManualFineSheet: { sheet = .manualFine },
            onPresentRemindAttendeesSheet: { sheet = .remindAttendees },
            onPresentCancelEventSheet: { sheet = .cancelEvent },
            onPresentCloseEventSheet: { sheet = .closeEvent },
            onPresentCancelAttendanceSheet: { sheet = .cancelAttendance },
            onPresentEditEvent: { onEditEvent(coordinator?.event ?? event) },
            onPresentAttendeesList: { sheet = .attendees },
            canIssueManualFine: canIssueManualFine
        )
    }

    /// Wraps CalendarExportService.addToCalendar para que el dispatcher
    /// del top-nav menu pueda invocarlo directo (sin pasar por
    /// ShareEventSheet). EventKit solicita authorization la primera vez
    /// dentro de addToCalendar — best-effort fail-soft.
    private func addToCalendarViaPresenter() {
        guard let service = calendarService else { return }
        // Coordinator's live event wins; fall back to the initial prop
        // for the brief window before bootstrap finishes.
        let resolvedEvent = coordinator?.event ?? event
        let vocabulary = group.eventVocabulary
        Task {
            _ = try? await service.addToCalendar(resolvedEvent, vocabulary: vocabulary)
        }
    }

    // MARK: - Async work

    /// Inbox handler — dispatches a tapped action to its natural route.
    /// RSVP-pending → focus the RSVP intent in place; fine-related →
    /// open the appropriate sheet; everything else falls back to a
    /// resolve mark-as-read so the action drops out of the list.
    @MainActor
    private func refreshAttentionActions() async {
        let pending = (try? await app.userActionRepo.pending(
            userId: currentUserId,
            groupId: group.id
        )) ?? []
        attentionActions = pending.filter { $0.referenceId == event.id && $0.resolvedAt == nil }
    }

    @MainActor
    private func openInboxAction(_ action: UserAction, coordinator: EventDetailCoordinator) async {
        switch action.actionType {
        case .rsvpPending:
            // Surface is already on screen — just resolve the prompt so
            // it stops nagging. The user RSVPs via the Primary Actions
            // CTA.
            try? await app.userActionRepo.resolve(actionId: action.id)
            await refreshAttentionActions()
        case .finePending, .fineVoided, .fineProposalReview, .appealVotePending:
            // Fines live in their own surface; resolve the inbox row so
            // it disappears, and let the user navigate via the host
            // actions or MyFines.
            try? await app.userActionRepo.resolve(actionId: action.id)
            await refreshAttentionActions()
        default:
            try? await app.userActionRepo.resolve(actionId: action.id)
            await refreshAttentionActions()
        }
    }

    /// Lazily build the sub-coordinator a sheet needs the first time it
    /// opens. Mirrors the original lifecycle pattern from `EventDetailView`:
    /// keeping coordinators stale-but-warm across open/close cycles so
    /// re-opening doesn't trigger redundant fetches.
    @MainActor
    private func prepareCoordinator(for kind: Sheet?) async {
        guard let kind, let coordinator else { return }
        switch kind {
        case .manualFine where manualFineCoordinator == nil:
            manualFineCoordinator = AddManualFineCoordinator(
                groupId: group.id,
                eventId: event.id,
                fineRepo: app.fineRepo,
                groupsRepo: app.groupsRepo
            )
        case .ledger where ledgerCoordinator == nil:
            let ctx = ResourceLedgerContext(
                groupId: event.groupId,
                resourceId: event.id,
                resourceType: "event",
                displayName: event.title,
                currentUserId: currentUserId
            )
            ledgerCoordinator = ResourceLedgerCoordinator(
                context: ctx,
                ledgerRepo: app.ledgerRepo,
                groupsRepo: app.groupsRepo,
                policyRepo: app.policyRepo
            )
        case .rules where rulesCoordinator == nil:
            let me = memberDirectory[currentUserId]?.member
            // Mig 00262: admin separó de founder. canCreate de rules
            // requiere permission, no identity — usamos isAdmin que
            // cubre founders (vía backfill) y admins explícitos.
            let isAdmin = me?.isAdmin == true
            let isHost = coordinator.event.hostId == currentUserId
            let ctx = ResourceRuleContext(
                groupId: event.groupId,
                resourceId: event.id,
                resourceType: "event",
                displayName: event.title,
                canCreate: isAdmin || isHost
            )
            rulesCoordinator = ResourceRulesCoordinator(
                context: ctx,
                ruleRepo: app.ruleRepo,
                shapeRegistry: app.ruleShapeRegistry
            )
        default:
            break
        }
    }

    // MARK: - New universal detail adapter (ResourceDetailContent)

    private static let dateFormatter: DateFormatter = {
        let f = DateFormatter()
        f.locale = Locale(identifier: "es_MX")
        f.dateFormat = "d MMM"
        return f
    }()

    private static let timeFormatter: DateFormatter = {
        let f = DateFormatter()
        f.locale = Locale(identifier: "es_MX")
        f.timeStyle = .short
        return f
    }()

    private func makeEventInput(coordinator: EventDetailCoordinator) -> EventInput {
        let e = coordinator.event
        let my = coordinator.myRSVP
        let viewerIsHost = coordinator.viewerIsHost
        // Hosts are implicitly attending their own event — they shouldn't
        // see the "Confirma asistencia" CTA, and they show up as going
        // even when the `event_attendance` row hasn't been auto-created
        // yet (some flows defer it until the host actually taps RSVP).
        let needsConfirm = !viewerIsHost && (my == nil || my?.status == .pending)
        let isGoing = viewerIsHost || my?.status == .going
        let isRecurrent = (recurrenceLabel != nil) || (e.seriesId != nil)
        return EventInput(
            id: e.id.uuidString,
            title: e.title,
            dateLabel: Self.dateFormatter.string(from: e.startsAt),
            timeLabel: Self.timeFormatter.string(from: e.startsAt),
            dayLabel: Self.dayLabel(for: e.startsAt),
            durationMin: e.durationMinutes,
            isHost: coordinator.viewerIsHost,
            needsRSVPConfirm: needsConfirm,
            viewerIsGoing: isGoing,
            address: e.locationName ?? "",
            coordinate: CLLocationCoordinate2D(
                latitude: e.locationLat ?? 19.4326,
                longitude: e.locationLng ?? -99.1332
            ),
            attendees: makeAttendees(rsvps: coordinator.rsvps),
            activity: (blocks?.activityHead ?? []).map(Self.mapActivityEntry),
            isRecurrent: isRecurrent,
            recurrenceLabel: recurrenceLabel
        )
    }

    /// Going + pending RSVPs → Person avatars in the Asistencia section.
    /// Tint pulls from `ResourceFamilyTint.persons` so the swatch stays
    /// consistent with the rest of the app's identity surface.
    private func makeAttendees(rsvps: [RSVP]) -> [Person] {
        let personTint = ResourceFamilyTint.persons.color
        return rsvps
            .filter { $0.status == .going || $0.status == .pending }
            .compactMap { rsvp -> Person? in
                let profile = memberDirectory[rsvp.userId]?.profile
                let name = profile?.displayName ?? "Miembro"
                let avatarURL = profile?.avatarUrl.flatMap(URL.init(string:))
                return Person(
                    id: rsvp.userId.uuidString,
                    name: name,
                    initials: Self.initials(from: name),
                    color: personTint,
                    imageURL: avatarURL
                )
            }
    }

    /// `ActivityEntry` already carries a pre-formatted `relativeTime`
    /// string ("hace 2h"). We pass it via `prebakedRelativeTime` so the
    /// new view skips its own RelativeDateTimeFormatter — otherwise
    /// `.now` timestamps would all render as "hace 0s".
    private static func mapActivityEntry(_ entry: ActivityEntry) -> ActivityItem {
        ActivityItem(
            id: entry.id.uuidString,
            title: entry.sentence,
            subtitle: nil,
            timestamp: .now,
            icon: entry.icon,
            kind: .neutral,
            prebakedRelativeTime: entry.relativeTime
        )
    }

    private static func initials(from name: String) -> String {
        let parts = name.split(separator: " ").prefix(2)
        let chars = parts.compactMap { $0.first }.map(String.init)
        let joined = chars.joined()
        return joined.isEmpty ? "?" : joined.uppercased()
    }

    /// Builds the recurrence label from the series pattern jsonb. Tries
    /// to extract the FrequencyType raw value first, falls back to
    /// "Recurrente · Ciclo N" when the cadence isn't decodable but a
    /// cycle number is present.
    private static func makeRecurrenceLabel(series: ResourceSeries, cycleNumber: Int?) -> String {
        if case .object(let root) = series.pattern,
           case .string(let raw) = root["frequency"],
           let freq = FrequencyType(rawValue: raw) {
            if let n = cycleNumber, n > 0 {
                return "Recurrente · \(freq.displayName) · Ciclo \(n)"
            }
            return "Recurrente · \(freq.displayName)"
        }
        if let n = cycleNumber, n > 0 {
            return "Recurrente · Ciclo \(n)"
        }
        return "Recurrente"
    }

    private static func dayLabel(for date: Date) -> String {
        let cal = Calendar.current
        if cal.isDateInToday(date)     { return "Hoy" }
        if cal.isDateInTomorrow(date)  { return "Mañana" }
        if cal.isDateInYesterday(date) { return "Ayer" }
        let f = DateFormatter()
        f.locale = Locale(identifier: "es_MX")
        f.dateFormat = "EEEE"
        return f.string(from: date).capitalized
    }

    /// Splices the parent `Group` into a freshly-built `ResourceConfig`
    /// so the new `GroupContextSlot` renders the persistent "En {group}"
    /// header under the identity ribbon. The dismiss callback on tap
    /// just closes the detail — the wider app routes group navigation
    /// from elsewhere.
    private func enrich(_ config: ResourceConfig, creatorName: String?) -> ResourceConfig {
        ResourceConfig(
            identity: config.identity,
            accent: config.accent,
            hero: config.hero,
            actions: config.actions,
            sections: config.sections,
            activity: config.activity,
            toolbarMenu: config.toolbarMenu,
            groupContext: GroupContextData(
                groupName: group.name,
                groupInitials: Self.groupInitials(group.name),
                proposedBy: creatorName,
                proposedAt: coordinator?.event.createdAt,
                onTapGroup: onClose
            ),
            // SharedMoney Phase 4 brick C fix: preserve moneyContext
            // through the enrich() wrapper. Without this the .event(...)
            // factory's moneyContext was being dropped before reaching
            // ResourceDetailContent — Money Block never rendered.
            moneyContext: config.moneyContext
        )
    }

    private func creatorDisplayName(for event: Event) -> String? {
        guard let id = event.createdBy else { return nil }
        return memberDirectory[id]?.profile?.displayName
    }

    private static func groupInitials(_ name: String) -> String {
        let chars = name.split(separator: " ").prefix(2).compactMap { $0.first }.map(String.init)
        return chars.joined().uppercased()
    }

    /// Builds the [...] menu with everything the heritage view exposed:
    /// universal actions (share, edit, calendar, wallet), governance
    /// (rules, ledger), host-only operations (remind, close, cancel),
    /// and the gated manual fine. Mirrors the routing in `handleOverflow`
    /// and the legacy `EventDetailSheets` so behaviour is unchanged —
    /// just relocated from the toolbar's bespoke menu to the
    /// `ResourceDetailContent` toolbar menu.
    private func makeToolbarMenu(coordinator: EventDetailCoordinator) -> [ToolbarMenuItem] {
        let isHost = coordinator.viewerIsHost
        var items: [ToolbarMenuItem] = [
            ToolbarMenuItem(label: "Compartir", icon: "square.and.arrow.up") {
                sheet = .share
            },
            ToolbarMenuItem(label: "Añadir al calendario", icon: "calendar.badge.plus") {
                addToCalendarViaPresenter()
            },
            ToolbarMenuItem(label: "Pase de Wallet", icon: "wallet.pass") {
                Task { _ = await coordinator.generateWalletPass() }
            }
        ]
        // Governance — always visible (read-only for non-admins)
        items.append(contentsOf: [
            ToolbarMenuItem(label: "Reglas", icon: "list.bullet.rectangle") {
                sheet = .rules
            },
            ToolbarMenuItem(label: "Libro", icon: "book") {
                sheet = .ledger
            }
        ])
        if canIssueManualFine {
            items.append(ToolbarMenuItem(label: "Multa manual", icon: "exclamationmark.bubble") {
                sheet = .manualFine
            })
        }
        // Host-only operations
        if isHost {
            items.append(contentsOf: [
                ToolbarMenuItem(label: "Editar evento", icon: "pencil") {
                    onEditEvent(coordinator.event)
                },
                ToolbarMenuItem(label: "Recordar a asistentes", icon: "bell.badge") {
                    sheet = .remindAttendees
                },
                ToolbarMenuItem(label: "Cerrar evento", icon: "lock") {
                    sheet = .closeEvent
                },
                ToolbarMenuItem(label: "Cancelar evento", icon: "xmark.circle", role: .destructive) {
                    sheet = .cancelEvent
                }
            ])
        }
        return items
    }
}
