import Foundation
import Supabase

/// Read + lifecycle ops for fines. Sprint 1c uses this for MyFinesView,
/// FineDetailView, ReviewProposedFinesView (host).
public protocol FineRepository: Actor {
    /// All fines for a user across all their groups, descending by createdAt.
    func myFines(userId: UUID) async throws -> [Fine]
    /// All fines for an event (host's grace-period review).
    func fines(forEventId: UUID) async throws -> [Fine]
    /// Single fine by id, or nil if invisible to caller (RLS).
    func fine(id: UUID) async throws -> Fine?

    /// Host-only: skip the 24h grace and officialize a proposed fine now.
    func officialize(fineId: UUID) async throws -> Fine
    /// Admin-only: annul a fine with optional reason (sets status=voided).
    func void(fineId: UUID, reason: String?) async throws -> Fine
    /// Admin-only: issue an ad-hoc fine outside the rule engine. Server
    /// inserts with status='officialized' (post-00028) so the fined user
    /// gets a finePending user_action immediately.
    ///
    /// `eventId` is the V1 cohabitation FK to `events`. `resourceId` is the
    /// polymorphic FK to `resources` (post-00041) — for V1 events the two
    /// are the same UUID via dual-write trigger 00039. Phase 2+ callers
    /// targeting non-event resources (slot, fund, position) pass
    /// `resourceId` and leave `eventId` nil.
    ///
    /// V1 default: caller passes only `eventId`; server coalesces
    /// `resource_id := coalesce(p_resource_id, p_event_id)`.
    func issueManual(
        groupId: UUID,
        userId: UUID,
        amount: Decimal,
        reason: String,
        eventId: UUID?,
        resourceId: UUID?
    ) async throws -> Fine
    /// User pays their own fine (legacy `pay_fine` RPC).
    func pay(fineId: UUID) async throws -> Fine
}

// MARK: - Mock

public actor MockFineRepository: FineRepository {
    public private(set) var fines: [Fine] = []

    /// Test hook: when true, the next call to `issueManual` throws and resets.
    private var throwOnIssueManual: Bool = false

    public func setThrowOnIssueManual(_ value: Bool) { throwOnIssueManual = value }

    /// Test hook: when true, the next call to `void` throws and resets.
    private var throwOnVoid: Bool = false
    /// Test hook: error message for the next thrown void. Default mirrors a
    /// realistic server raise for humanize() coverage.
    private var voidErrorMessage: String = "only admins can void fines"

    public func setThrowOnVoid(_ value: Bool) { throwOnVoid = value }
    public func setVoidErrorMessage(_ message: String) { voidErrorMessage = message }

    public init(seed: [Fine] = []) { self.fines = seed }

    public func myFines(userId: UUID) async throws -> [Fine] {
        fines.filter { $0.userId == userId }.sorted { $0.createdAt > $1.createdAt }
    }

    public func fines(forEventId: UUID) async throws -> [Fine] {
        fines.filter { $0.eventId == forEventId }
    }

    public func fine(id: UUID) async throws -> Fine? {
        fines.first { $0.id == id }
    }

    public func officialize(fineId: UUID) async throws -> Fine {
        try update(fineId: fineId) { f in
            Fine(
                id: f.id, groupId: f.groupId, userId: f.userId, ruleId: f.ruleId,
                eventId: f.eventId, reason: f.reason, amount: f.amount,
                status: .officialized, paid: f.paid, paidAt: f.paidAt,
                waived: f.waived, waivedAt: f.waivedAt, waivedReason: f.waivedReason,
                autoGenerated: f.autoGenerated, issuedBy: f.issuedBy,
                details: f.details, ruleSnapshot: f.ruleSnapshot,
                createdAt: f.createdAt, updatedAt: .now
            )
        }
    }

    public func void(fineId: UUID, reason: String?) async throws -> Fine {
        if throwOnVoid {
            throwOnVoid = false
            throw NSError(
                domain: "MockFineRepository",
                code: -1,
                userInfo: [NSLocalizedDescriptionKey: voidErrorMessage]
            )
        }
        return try update(fineId: fineId) { f in
            Fine(
                id: f.id, groupId: f.groupId, userId: f.userId, ruleId: f.ruleId,
                eventId: f.eventId, reason: f.reason, amount: f.amount,
                status: .voided, paid: f.paid, paidAt: f.paidAt,
                waived: true, waivedAt: .now, waivedReason: reason,
                autoGenerated: f.autoGenerated, issuedBy: f.issuedBy,
                details: f.details, ruleSnapshot: f.ruleSnapshot,
                createdAt: f.createdAt, updatedAt: .now
            )
        }
    }

    public func issueManual(
        groupId: UUID,
        userId: UUID,
        amount: Decimal,
        reason: String,
        eventId: UUID?,
        resourceId: UUID?
    ) async throws -> Fine {
        if throwOnIssueManual {
            throwOnIssueManual = false
            throw NSError(domain: "MockFineRepository", code: -1, userInfo: [NSLocalizedDescriptionKey: "admin only"])
        }
        let fine = Fine(
            id: UUID(),
            groupId: groupId,
            userId: userId,
            ruleId: nil,
            eventId: eventId,
            resourceId: resourceId ?? eventId,
            reason: reason,
            amount: amount,
            status: .officialized,
            paid: false,
            paidAt: nil,
            waived: false,
            waivedAt: nil,
            waivedReason: nil,
            autoGenerated: false,
            issuedBy: UUID(),
            details: nil,
            ruleSnapshot: nil,
            createdAt: .now,
            updatedAt: .now
        )
        fines.append(fine)
        return fine
    }

    public func pay(fineId: UUID) async throws -> Fine {
        try update(fineId: fineId) { f in
            Fine(
                id: f.id, groupId: f.groupId, userId: f.userId, ruleId: f.ruleId,
                eventId: f.eventId, reason: f.reason, amount: f.amount,
                status: .paid, paid: true, paidAt: .now,
                waived: f.waived, waivedAt: f.waivedAt, waivedReason: f.waivedReason,
                autoGenerated: f.autoGenerated, issuedBy: f.issuedBy,
                details: f.details, ruleSnapshot: f.ruleSnapshot,
                createdAt: f.createdAt, updatedAt: .now
            )
        }
    }

    private func update(fineId: UUID, transform: (Fine) -> Fine) throws -> Fine {
        guard let idx = fines.firstIndex(where: { $0.id == fineId }) else {
            throw NSError(domain: "MockFineRepository", code: 404)
        }
        let updated = transform(fines[idx])
        fines[idx] = updated
        return updated
    }
}

// MARK: - Live

public actor LiveFineRepository: FineRepository {
    private let client: SupabaseClient
    public init(client: SupabaseClient) { self.client = client }

    public func myFines(userId: UUID) async throws -> [Fine] {
        // §14 Step 3b: read from fines_view (status/paid/waived derived
        // from atoms + votes + review_periods). Writes still go to the
        // fines table via RPCs (issue_manual_fine, officialize_fine,
        // pay_fine, void_fine, start_fine_appeal).
        try await client
            .from("fines_view")
            .select("*")
            .eq("user_id", value: userId.uuidString.lowercased())
            .order("created_at", ascending: false)
            .execute()
            .value
    }

    public func fines(forEventId: UUID) async throws -> [Fine] {
        try await client
            .from("fines_view")
            .select("*")
            .eq("event_id", value: forEventId.uuidString.lowercased())
            .order("created_at", ascending: false)
            .execute()
            .value
    }

    public func fine(id: UUID) async throws -> Fine? {
        try? await client
            .from("fines_view")
            .select("*")
            .eq("id", value: id.uuidString.lowercased())
            .single()
            .execute()
            .value
    }

    public func officialize(fineId: UUID) async throws -> Fine {
        struct Params: Encodable { let p_fine_id: String }
        return try await client
            .rpc("officialize_fine", params: Params(p_fine_id: fineId.uuidString.lowercased()))
            .execute()
            .value
    }

    public func void(fineId: UUID, reason: String?) async throws -> Fine {
        struct Params: Encodable {
            let p_fine_id: String
            let p_reason: String?
        }
        return try await client
            .rpc("void_fine", params: Params(
                p_fine_id: fineId.uuidString.lowercased(),
                p_reason: reason
            ))
            .execute()
            .value
    }

    public func issueManual(
        groupId: UUID,
        userId: UUID,
        amount: Decimal,
        reason: String,
        eventId: UUID?,
        resourceId: UUID?
    ) async throws -> Fine {
        struct Params: Encodable {
            let p_group_id: String
            let p_user_id: String
            let p_amount: Decimal
            let p_reason: String
            let p_rule_id: String?
            let p_event_id: String?
            let p_resource_id: String?
        }
        return try await client
            .rpc("issue_manual_fine", params: Params(
                p_group_id: groupId.uuidString.lowercased(),
                p_user_id: userId.uuidString.lowercased(),
                p_amount: amount,
                p_reason: reason,
                p_rule_id: nil,
                p_event_id: eventId?.uuidString.lowercased(),
                p_resource_id: (resourceId ?? eventId)?.uuidString.lowercased()
            ))
            .execute()
            .value
    }

    public func pay(fineId: UUID) async throws -> Fine {
        // §14 Step 3a/3b: pay_fine RPC handles the fines table write +
        // emits the fine_paid atom that the projection reads. Earlier
        // versions did a raw UPDATE bypassing the RPC, which skipped the
        // atom emission and the permission/fund-balance checks. RPC
        // returns void, so we re-fetch from fines_view to get derived
        // status='paid'.
        struct Params: Encodable { let p_fine_id: String }
        try await client
            .rpc("pay_fine", params: Params(p_fine_id: fineId.uuidString.lowercased()))
            .execute()
        guard let updated = try await fine(id: fineId) else {
            throw NSError(domain: "LiveFineRepository", code: 404)
        }
        return updated
    }
}
