import Testing
import Foundation
import RuulCore
@testable import RuulFeatures

@Suite("FineBlockBuilder")
@MainActor
struct FineBlockBuilderTests {

    @Test("unpaid fine for debtor → urgent + payFine primary action")
    func unpaidForDebtor() {
        let builder = FineBlockBuilder()
        let fine    = TestFixtures.unpaidFineForViewer()
        let viewer  = TestFixtures.guestViewerContext()
        let blocks  = builder.build(source: fine, viewer: viewer, now: TestFixtures.now)

        #expect(blocks.state.urgency == .urgent)
        #expect(blocks.state.primaryAction?.kind == .payFine)
        #expect(blocks.state.primaryAction?.label.lowercased().contains("pagar") == true)
    }

    @Test("paid fine renders terminal headline + no primary action")
    func paidFine() {
        let fine   = TestFixtures.paidFine()
        let blocks = FineBlockBuilder().build(
            source: fine,
            viewer: TestFixtures.guestViewerContext(),
            now: TestFixtures.now
        )
        #expect(blocks.state.urgency == .terminal)
        #expect(blocks.state.primaryAction == nil)
        #expect(blocks.state.headline.lowercased().contains("pagada"))
    }

    @Test("observer (non-debtor) sees ambient urgency, no primary action")
    func observerUnpaid() {
        // Create a fine where debtor is hostUserId (not the viewer)
        let fine = Fine(
            id: UUID(),
            groupId: TestFixtures.groupId,
            userId: TestFixtures.hostUserId,   // different from viewerUserId
            ruleId: nil,
            eventId: nil,
            reason: "Canceló el día anterior",
            amount: 150,
            status: .officialized,
            paid: false,
            paidAt: nil,
            waived: false,
            waivedAt: nil,
            waivedReason: nil,
            autoGenerated: false,
            issuedBy: TestFixtures.viewerUserId,
            details: nil,
            ruleSnapshot: nil,
            createdAt: TestFixtures.now,
            updatedAt: TestFixtures.now
        )
        let blocks = FineBlockBuilder().build(
            source: fine,
            viewer: TestFixtures.guestViewerContext(),   // viewer != debtor
            now: TestFixtures.now
        )
        #expect(blocks.state.urgency == .ambient)
        #expect(blocks.state.primaryAction == nil)
    }

    @Test("fine has amount capability block with balance layout")
    func amountBlock() {
        let fine   = TestFixtures.unpaidFineForViewer()
        let blocks = FineBlockBuilder().build(
            source: fine,
            viewer: TestFixtures.guestViewerContext(),
            now: TestFixtures.now
        )
        let amtBlock = blocks.capabilities.first { $0.id == "amount" }
        #expect(amtBlock != nil)
        #expect(amtBlock?.layoutKind == .balance)
    }
}
