import Foundation
import RuulCore
@testable import RuulFeatures

// MARK: - TestFixtures
// Uses REAL entity types (EventDetailSnapshot, Fine, Vote, ResourceRow)
// per Addendum F doctrine. No synthetic source structs in production.

enum TestFixtures {
    // MARK: Stable identifiers

    static let now            = Date(timeIntervalSince1970: 1_780_000_000)
    static let groupId        = UUID()
    static let viewerUserId   = UUID()
    static let hostUserId     = UUID()
    static let viewerMemberId = UUID()

    // MARK: BlockViewerContext

    static func guestViewerContext() -> BlockViewerContext {
        BlockViewerContext(
            userId: viewerUserId,
            permissions: [],
            activeModules: ["rsvp", "rotating_host"],
            memberId: viewerMemberId
        )
    }

    static func hostViewerContext() -> BlockViewerContext {
        BlockViewerContext(
            userId: hostUserId,
            permissions: [.manageEvents],
            activeModules: ["rsvp", "rotating_host"],
            memberId: UUID()
        )
    }

    // MARK: EventDetailSnapshot helpers

    /// Scheduled event (starts tomorrow).
    static func scheduledEventSnapshot(
        hostIsViewer: Bool = false,
        rsvpForViewer: RSVP? = nil,
        locationName: String? = nil,
        rotationConfig: RotationSnapshotInput? = nil
    ) -> EventDetailSnapshot {
        let hostId: UUID = hostIsViewer ? viewerUserId : hostUserId
        let event = Event(
            id: UUID(),
            groupId: groupId,
            title: "Cena de los miércoles",
            startsAt: now.addingTimeInterval(86_400),
            locationName: locationName,
            hostId: hostId,
            status: .upcoming,
            createdAt: now.addingTimeInterval(-86_400)
        )
        return EventDetailSnapshot(
            event: event,
            myRSVP: rsvpForViewer,
            rotationConfig: rotationConfig,
            cycleNumber: 3,
            memberDirectory: [:],
            viewerIsHost: hostIsViewer
        )
    }

    /// Closed (completed) event.
    static func closedEventSnapshot() -> EventDetailSnapshot {
        let event = Event(
            id: UUID(),
            groupId: groupId,
            title: "Cena pasada",
            startsAt: now.addingTimeInterval(-86_400),
            hostId: hostUserId,
            status: .closed,
            createdAt: now.addingTimeInterval(-172_800)
        )
        return EventDetailSnapshot(
            event: event,
            myRSVP: makeBareRSVP(eventId: event.id, userId: viewerUserId, status: .going),
            rotationConfig: nil,
            cycleNumber: 2,
            memberDirectory: [:],
            viewerIsHost: false
        )
    }

    // MARK: RSVP helpers

    static func makeBareRSVP(eventId: UUID, userId: UUID, status: RSVPStatus) -> RSVP {
        RSVP(
            id: UUID(),
            eventId: eventId,
            userId: userId,
            status: status
        )
    }

    // MARK: Fine helpers

    /// Unpaid fine where viewer is the debtor.
    static func unpaidFineForViewer() -> Fine {
        Fine(
            id: UUID(),
            groupId: groupId,
            userId: viewerUserId,
            ruleId: nil,
            eventId: nil,
            reason: "Llegada tarde",
            amount: 200,
            status: .officialized,
            paid: false,
            paidAt: nil,
            waived: false,
            waivedAt: nil,
            waivedReason: nil,
            autoGenerated: true,
            issuedBy: nil,
            details: nil,
            ruleSnapshot: nil,
            createdAt: now.addingTimeInterval(-3600),
            updatedAt: now.addingTimeInterval(-3600)
        )
    }

    /// Paid fine.
    static func paidFine() -> Fine {
        Fine(
            id: UUID(),
            groupId: groupId,
            userId: viewerUserId,
            ruleId: nil,
            eventId: nil,
            reason: "Llegada tarde",
            amount: 200,
            status: .paid,
            paid: true,
            paidAt: now.addingTimeInterval(-1800),
            waived: false,
            waivedAt: nil,
            waivedReason: nil,
            autoGenerated: true,
            issuedBy: nil,
            details: nil,
            ruleSnapshot: nil,
            createdAt: now.addingTimeInterval(-86_400),
            updatedAt: now.addingTimeInterval(-1800)
        )
    }

    // MARK: Vote helpers

    /// Open vote where viewer has not yet voted.
    static func openVoteNotVoted(totalEligible: Int = 8, cast: Int = 3) -> Vote {
        Vote(
            id: UUID(),
            groupId: groupId,
            voteType: .ruleChange,
            referenceId: UUID(),
            title: "Cambiar regla de llegada",
            description: nil,
            createdByMemberId: nil,
            openedAt: now.addingTimeInterval(-3600),
            closesAt: now.addingTimeInterval(86_400),
            resolvedAt: nil,
            quorumPercent: 51,
            thresholdPercent: 51,
            isAnonymous: false,
            status: .open,
            counts: VoteCounts(
                inFavor: cast,
                against: 0,
                abstained: 0,
                pending: totalEligible - cast,
                totalEligible: totalEligible,
                resolution: nil
            ),
            payload: .object([:])
        )
    }

    /// Closed (resolved) vote.
    static func closedVote(totalEligible: Int = 8) -> Vote {
        Vote(
            id: UUID(),
            groupId: groupId,
            voteType: .ruleChange,
            referenceId: UUID(),
            title: "Cambio aprobado",
            description: nil,
            createdByMemberId: nil,
            openedAt: now.addingTimeInterval(-172_800),
            closesAt: now.addingTimeInterval(-86_400),
            resolvedAt: now.addingTimeInterval(-86_400),
            quorumPercent: 51,
            thresholdPercent: 51,
            isAnonymous: false,
            status: .resolved,
            counts: VoteCounts(
                inFavor: totalEligible,
                against: 0,
                abstained: 0,
                pending: 0,
                totalEligible: totalEligible,
                resolution: .passed
            ),
            payload: .object([:])
        )
    }

    // MARK: ResourceRow helpers

    static func activeFundRow(balanceCents: Int? = 430_000) -> ResourceRow {
        var meta: [String: JSONConfig] = [
            "name": .string("Fondo común"),
            "currency": .string("MXN")
        ]
        if let cents = balanceCents {
            meta["balance_cents"] = .int(cents)
        }
        return ResourceRow(
            id: UUID(),
            groupId: groupId,
            resourceType: .fund,
            status: "active",
            metadata: .object(meta),
            createdAt: now.addingTimeInterval(-86_400),
            updatedAt: now
        )
    }

    static func lockedFundRow() -> ResourceRow {
        let meta: [String: JSONConfig] = [
            "name": .string("Fondo congelado"),
            "currency": .string("MXN"),
            "balance_cents": .int(0),
            "locked": .bool(true)
        ]
        return ResourceRow(
            id: UUID(),
            groupId: groupId,
            resourceType: .fund,
            status: "active",
            metadata: .object(meta),
            createdAt: now.addingTimeInterval(-86_400),
            updatedAt: now
        )
    }
}
