// AUTOGENERATED. Do not edit. Source: ios/Packages/RuulCore/Sources/RuulCore/PlatformModels/ConsequenceType.swift
// Run: make gen

export const consequenceTypeValues = [
  "fine",
  "loseTurn",
  "losePriority",
  "serviceCompensation",
  "blockTemporary",
  "reciprocity",
  "logOnly",
  "sumPoints",
  "subtractPoints",
  "sendNotification",
  "startVote",
  "createEvent",
  "assignSlot",
  "transferRight",
  "callWebhook",
  "emitWarning",
  "revokeRight",
  "suspendRight",
  "requireApproval",
  "lockBookings",
  "releaseBooking",
  "denyAction",
  "bumpPriority",
] as const;

export type ConsequenceType = (typeof consequenceTypeValues)[number];

export function isConsequenceType(value: string): value is ConsequenceType {
  return (consequenceTypeValues as readonly string[]).includes(value);
}
