// AUTOGENERATED. Do not edit. Source: ios/Packages/RuulCore/Sources/RuulCore/PlatformModels/ResourceType.swift
// Run: make gen

export const resourceTypeValues = [
  "event",
  "fund",
  "asset",
  "space",
  "slot",
  "right",
] as const;

export type ResourceType = (typeof resourceTypeValues)[number];

export function isResourceType(value: string): value is ResourceType {
  return (resourceTypeValues as readonly string[]).includes(value);
}
