import Foundation
import Supabase

/// Read + lifecycle ops for fines. Sprint 1c uses this for MyFinesView,
/// FineDetailView, ReviewProposedFinesView (host).
public protocol FineRepository: Actor {
    /// All fines for a user across all their groups, descending by createdAt.
    func myFines(userId: UUID) async throws -> [Fine]
    /// All fines for an event (host's grace-period review).
    func fines(forEventId: UUID) async throws -> [Fine]
    /// Single fine by id, or nil if invisible to caller (RLS).
    func fine(id: UUID) async throws -> Fine?

    /// Host-only: skip the 24h grace and officialize a proposed fine now.
    func officialize(fineId: UUID) async throws -> Fine
    /// Admin-only: annul a fine with optional reason (sets status=voided).
    func void(fineId: UUID, reason: String?) async throws -> Fine
    /// User pays their own fine (legacy `pay_fine` RPC).
    func pay(fineId: UUID) async throws -> Fine
}

// MARK: - Mock

public actor MockFineRepository: FineRepository {
    public private(set) var fines: [Fine] = []

    public init(seed: [Fine] = []) { self.fines = seed }

    public func myFines(userId: UUID) async throws -> [Fine] {
        fines.filter { $0.userId == userId }.sorted { $0.createdAt > $1.createdAt }
    }

    public func fines(forEventId: UUID) async throws -> [Fine] {
        fines.filter { $0.eventId == forEventId }
    }

    public func fine(id: UUID) async throws -> Fine? {
        fines.first { $0.id == id }
    }

    public func officialize(fineId: UUID) async throws -> Fine {
        try update(fineId: fineId) { f in
            Fine(
                id: f.id, groupId: f.groupId, userId: f.userId, ruleId: f.ruleId,
                eventId: f.eventId, reason: f.reason, amount: f.amount,
                status: .officialized, paid: f.paid, paidAt: f.paidAt,
                waived: f.waived, waivedAt: f.waivedAt, waivedReason: f.waivedReason,
                autoGenerated: f.autoGenerated, issuedBy: f.issuedBy,
                details: f.details, ruleSnapshot: f.ruleSnapshot,
                createdAt: f.createdAt, updatedAt: .now
            )
        }
    }

    public func void(fineId: UUID, reason: String?) async throws -> Fine {
        try update(fineId: fineId) { f in
            Fine(
                id: f.id, groupId: f.groupId, userId: f.userId, ruleId: f.ruleId,
                eventId: f.eventId, reason: f.reason, amount: f.amount,
                status: .voided, paid: f.paid, paidAt: f.paidAt,
                waived: true, waivedAt: .now, waivedReason: reason,
                autoGenerated: f.autoGenerated, issuedBy: f.issuedBy,
                details: f.details, ruleSnapshot: f.ruleSnapshot,
                createdAt: f.createdAt, updatedAt: .now
            )
        }
    }

    public func pay(fineId: UUID) async throws -> Fine {
        try update(fineId: fineId) { f in
            Fine(
                id: f.id, groupId: f.groupId, userId: f.userId, ruleId: f.ruleId,
                eventId: f.eventId, reason: f.reason, amount: f.amount,
                status: .paid, paid: true, paidAt: .now,
                waived: f.waived, waivedAt: f.waivedAt, waivedReason: f.waivedReason,
                autoGenerated: f.autoGenerated, issuedBy: f.issuedBy,
                details: f.details, ruleSnapshot: f.ruleSnapshot,
                createdAt: f.createdAt, updatedAt: .now
            )
        }
    }

    private func update(fineId: UUID, transform: (Fine) -> Fine) throws -> Fine {
        guard let idx = fines.firstIndex(where: { $0.id == fineId }) else {
            throw NSError(domain: "MockFineRepository", code: 404)
        }
        let updated = transform(fines[idx])
        fines[idx] = updated
        return updated
    }
}

// MARK: - Live

public actor LiveFineRepository: FineRepository {
    private let client: SupabaseClient
    public init(client: SupabaseClient) { self.client = client }

    public func myFines(userId: UUID) async throws -> [Fine] {
        try await client
            .from("fines")
            .select("*")
            .eq("user_id", value: userId.uuidString.lowercased())
            .order("created_at", ascending: false)
            .execute()
            .value
    }

    public func fines(forEventId: UUID) async throws -> [Fine] {
        try await client
            .from("fines")
            .select("*")
            .eq("event_id", value: forEventId.uuidString.lowercased())
            .order("created_at", ascending: false)
            .execute()
            .value
    }

    public func fine(id: UUID) async throws -> Fine? {
        try? await client
            .from("fines")
            .select("*")
            .eq("id", value: id.uuidString.lowercased())
            .single()
            .execute()
            .value
    }

    public func officialize(fineId: UUID) async throws -> Fine {
        struct Params: Encodable { let p_fine_id: String }
        return try await client
            .rpc("officialize_fine", params: Params(p_fine_id: fineId.uuidString.lowercased()))
            .execute()
            .value
    }

    public func void(fineId: UUID, reason: String?) async throws -> Fine {
        struct Params: Encodable {
            let p_fine_id: String
            let p_reason: String?
        }
        return try await client
            .rpc("void_fine", params: Params(
                p_fine_id: fineId.uuidString.lowercased(),
                p_reason: reason
            ))
            .execute()
            .value
    }

    public func pay(fineId: UUID) async throws -> Fine {
        // Legacy pay_fine RPC sets paid=true; the on_fine_status_change
        // trigger will flip status to 'paid'. Use raw update for now since
        // pay_fine returns void, not the row.
        struct Update: Encodable {
            let paid: Bool
            let paid_at: String
            let status: String
        }
        try await client
            .from("fines")
            .update(Update(
                paid: true,
                paid_at: ISO8601DateFormatter().string(from: .now),
                status: "paid"
            ))
            .eq("id", value: fineId.uuidString.lowercased())
            .execute()
        guard let updated = try await fine(id: fineId) else {
            throw NSError(domain: "LiveFineRepository", code: 404)
        }
        return updated
    }
}
