// AUTOGENERATED. Do not edit. Source: ios/Tandas/Platform/Models/ConditionType.swift
// Run: make gen

export const conditionTypeValues = [
  "alwaysTrue",
  "responseStatusIs",
  "checkInExists",
  "checkInMinutesLate",
  "eventDescriptionMissing",
  "minutesAfterScheduled",
  "hoursBeforeEvent",
  "memberHasMultipleFines",
  "memberFinesAbove",
  "memberMissedConsecutive",
  "eventDayOfWeek",
  "eventTimeWindow",
  "fundBalanceAbove",
  "fundBalanceBelow",
  "rotationPositionEquals",
] as const;

export type ConditionType = (typeof conditionTypeValues)[number];

export function isConditionType(value: string): value is ConditionType {
  return (conditionTypeValues as readonly string[]).includes(value);
}
