// AUTOGENERATED. Do not edit. Source: ios/Tandas/Platform/Models/ConsequenceType.swift
// Run: make gen

export const consequenceTypeValues = [
  "fine",
  "loseTurn",
  "losePriority",
  "serviceCompensation",
  "blockTemporary",
  "reciprocity",
  "logOnly",
  "sumPoints",
  "subtractPoints",
  "sendNotification",
  "startVote",
  "createEvent",
  "assignSlot",
  "transferRight",
  "callWebhook",
] as const;

export type ConsequenceType = (typeof consequenceTypeValues)[number];

export function isConsequenceType(value: string): value is ConsequenceType {
  return (consequenceTypeValues as readonly string[]).includes(value);
}
