// AUTOGENERATED. Do not edit. Source: ios/Tandas/Platform/Models/PermissionLevel.swift
// Run: make gen

export const permissionLevelValues = [
  "founder",
  "anyMember",
  "majorityVote",
  "supermajorityVote",
  "host",
  "treasurer",
] as const;

export type PermissionLevel = (typeof permissionLevelValues)[number];

export function isPermissionLevel(value: string): value is PermissionLevel {
  return (permissionLevelValues as readonly string[]).includes(value);
}
