// AUTOGENERATED. Do not edit. Source: ios/Packages/RuulCore/Sources/RuulCore/PlatformModels/Permission.swift
// Run: make gen

export const permissionValues = [
  "modifyGovernance",
  "modifyRules",
  "modifyMembers",
  "assignRoles",
  "removeMember",
  "issueFine",
  "voidFine",
  "markFinePaid",
  "closeAppeal",
  "createVotes",
  "castVote",
  "manageEvents",
  "manageModules",
  "assignSlot",
  "bookSlot",
  "approveSlotSwap",
  "fundContribute",
  "fundWithdraw",
  "fundAudit",
  "expenseSubmit",
  "expenseApprove",
  "transferRight",
  "delegateRight",
  "revokeRight",
  "suspendRight",
  "exerciseRight",
] as const;

export type Permission = (typeof permissionValues)[number];

export function isPermission(value: string): value is Permission {
  return (permissionValues as readonly string[]).includes(value);
}
