// AUTOGENERATED. Do not edit. Source: ios/Packages/RuulCore/Sources/RuulCore/PlatformModels/ResourceType.swift
// Run: make gen

export const resourceTypeValues = [
  "event",
  "slot",
  "booking",
  "fund",
  "position",
  "assignment",
  "rotation",
  "asset",
  "guestPass",
  "contribution",
  "proposal",
] as const;

export type ResourceType = (typeof resourceTypeValues)[number];

export function isResourceType(value: string): value is ResourceType {
  return (resourceTypeValues as readonly string[]).includes(value);
}
