// AUTOGENERATED. Do not edit. Source: ios/Tandas/Platform/Models/ResourceType.swift
// Run: make gen

export const resourceTypeValues = [
  "event",
  "slot",
  "fund",
  "position",
  "asset",
  "contribution",
] as const;

export type ResourceType = (typeof resourceTypeValues)[number];

export function isResourceType(value: string): value is ResourceType {
  return (resourceTypeValues as readonly string[]).includes(value);
}
