// AUTOGENERATED. Do not edit. Source: ios/Tandas/Platform/Models/SystemEventType.swift
// Run: make gen

export const systemEventTypeValues = [
  "eventClosed",
  "eventCreated",
  "rsvpDeadlinePassed",
  "hoursBeforeEvent",
  "rsvpSubmitted",
  "rsvpChangedSameDay",
  "checkInRecorded",
  "checkInMissed",
  "eventDescriptionMissing",
  "slotAssigned",
  "slotDeclined",
  "slotExpired",
  "fineOfficialized",
  "finePaid",
  "fineReminderSent",
  "appealCreated",
  "appealResolved",
  "voteOpened",
  "voteCast",
  "voteResolved",
  "fundDeposit",
  "fundThresholdReached",
  "positionChanged",
  "memberJoined",
  "memberLeft",
  "ruleEnabledChanged",
  "ruleAmountChanged",
] as const;

export type SystemEventType = (typeof systemEventTypeValues)[number];

export function isSystemEventType(value: string): value is SystemEventType {
  return (systemEventTypeValues as readonly string[]).includes(value);
}
