#!/bin/bash
# ci_post_clone.sh — Xcode Cloud post-clone hook.
#
# Why this exists
# ===============
# `ios/Tandas.xcodeproj` is gitignored. The canonical project description
# lives in `ios/project.yml` and is regenerated by xcodegen whenever
# Swift files are added/removed (see CLAUDE.md: "xcodegen generate cuando
# agregues/borres archivos .swift; xcodeproj está gitignored").
#
# Xcode Cloud workers clone the repo and immediately invoke
# `xcodebuild -resolvePackageDependencies -project .../Tandas.xcodeproj`.
# Without this hook the worker fails with:
#   "/Volumes/workspace/repository/ios/Tandas.xcodeproj does not exist."
#
# Apple convention: the `ci_scripts/` directory must sit next to the
# .xcodeproj. The worker runs this file with CWD = the script's
# directory, so we cd up one level to where project.yml lives.

set -euo pipefail

echo "→ Installing xcodegen (via Homebrew, pre-installed on Xcode Cloud)..."
brew install xcodegen

# CWD is ios/ci_scripts/; project.yml is at ios/project.yml.
cd "$(dirname "$0")/.."

echo "→ Generating Tandas.xcodeproj from project.yml..."
xcodegen generate

echo "→ Project regenerated; xcodebuild can now proceed."
