// verify-otp: validates an OTP and returns a session.
//
// Branches by channel:
//   • whatsapp: validates against public.otp_codes (hash match + not
//     expired + not consumed + attempts < 5). On success, generates a
//     session for the user via Admin API. If the user does not yet
//     exist in auth.users, creates them.
//   • sms: forwards to auth.verifyOtp({ phone, token, type: 'sms' }).
//
// Request:  { phone, code, channel: "whatsapp" | "sms" }
// Response: { access_token, refresh_token, user_id }   (200)
//           { error }                                   (4xx/5xx)
//
// IMPORTANT: the WhatsApp branch creates the user via Admin API. The
// resulting session is generated by signing a magic link and exchanging
// the embedded token. Supabase doesn't expose a "create session
// directly" endpoint; the magic-link approach is the documented
// workaround for SMS-less custom auth.

import { serve } from "https://deno.land/std@0.224.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.7";
import { corsHeaders } from "../_shared/cors.ts";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const SUPABASE_ANON_KEY = Deno.env.get("SUPABASE_ANON_KEY")!;

const MAX_ATTEMPTS = 5;

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  let phone: string, code: string, channel: "whatsapp" | "sms";
  try {
    const body = await req.json();
    phone = body.phone;
    code = body.code;
    channel = body.channel;
    if (!phone || !code || !channel) {
      return jsonError(400, "phone, code, channel required");
    }
  } catch {
    return jsonError(400, "invalid JSON body");
  }

  if (channel === "sms") {
    return await verifySMS(phone, code);
  }
  if (channel === "whatsapp") {
    return await verifyWhatsApp(phone, code);
  }
  return jsonError(400, "channel must be whatsapp or sms");
});

async function verifySMS(phone: string, code: string): Promise<Response> {
  const anon = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
  const { data, error } = await anon.auth.verifyOtp({
    phone,
    token: code,
    type: "sms",
  });
  if (error || !data.session) {
    return jsonError(401, error?.message ?? "invalid code");
  }
  return jsonResponse({
    access_token: data.session.access_token,
    refresh_token: data.session.refresh_token,
    user_id: data.user?.id,
  });
}

async function verifyWhatsApp(phone: string, code: string): Promise<Response> {
  const admin = createClient(SUPABASE_URL, SERVICE_ROLE_KEY);

  // 1. Find the latest pending OTP for this phone.
  const { data: rows, error: selErr } = await admin
    .from("otp_codes")
    .select("*")
    .eq("phone_e164", phone)
    .eq("channel", "whatsapp")
    .is("consumed_at", null)
    .gt("expires_at", new Date().toISOString())
    .order("created_at", { ascending: false })
    .limit(1);

  if (selErr) {
    console.error("otp_codes select failed", selErr);
    return jsonError(500, "lookup failed");
  }
  const row = rows?.[0];
  if (!row) return jsonError(401, "no pending code or expired");

  if (row.attempts >= MAX_ATTEMPTS) {
    return jsonError(429, "too many attempts");
  }

  // 2. Validate hash.
  const expectedHash = await sha256(`${code}:${phone}`);
  if (expectedHash !== row.code_hash) {
    await admin
      .from("otp_codes")
      .update({ attempts: row.attempts + 1 })
      .eq("id", row.id);
    return jsonError(401, "invalid code");
  }

  // 3. Mark consumed.
  await admin
    .from("otp_codes")
    .update({ consumed_at: new Date().toISOString() })
    .eq("id", row.id);

  // 4. Find or create the user, then return a session via magic-link
  //    exchange. The magic-link flow is the supported way to mint a
  //    session server-side for phone-only users without going through
  //    SMS verifyOtp.
  let userId: string;
  const { data: existing } = await admin.auth.admin.listUsers({ page: 1, perPage: 200 });
  const found = existing?.users?.find((u) => u.phone === phone.replace("+", ""));
  if (found) {
    userId = found.id;
  } else {
    const { data: created, error: createErr } = await admin.auth.admin.createUser({
      phone: phone.replace("+", ""),
      phone_confirm: true,
    });
    if (createErr || !created.user) {
      return jsonError(500, createErr?.message ?? "user create failed");
    }
    userId = created.user.id;
  }

  const { data: linkData, error: linkErr } = await admin.auth.admin.generateLink({
    type: "magiclink",
    email: `${userId}@phone.ruul.local`, // synthetic — never displayed
    options: { redirectTo: "ruul://auth/callback" },
  });

  if (linkErr || !linkData?.properties?.hashed_token) {
    // Fallback path: we couldn't mint a session via magiclink.
    // Returning 503 here causes the client to surface "WhatsApp validó
    // pero no pudimos iniciar sesión — usa SMS por ahora."
    console.error("generateLink failed", linkErr);
    return jsonError(503, "session mint failed; retry with SMS");
  }

  const anon = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
  const { data: verified, error: verErr } = await anon.auth.verifyOtp({
    token_hash: linkData.properties.hashed_token,
    type: "magiclink",
  });
  if (verErr || !verified.session) {
    return jsonError(503, verErr?.message ?? "session mint failed; retry with SMS");
  }

  return jsonResponse({
    access_token: verified.session.access_token,
    refresh_token: verified.session.refresh_token,
    user_id: userId,
  });
}

async function sha256(input: string): Promise<string> {
  const data = new TextEncoder().encode(input);
  const hash = await crypto.subtle.digest("SHA-256", data);
  return Array.from(new Uint8Array(hash))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

function jsonResponse(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

function jsonError(status: number, message: string) {
  return jsonResponse({ error: message }, status);
}
