import Foundation
import XCTest
@testable import Tandas

@MainActor
final class AddManualFineCoordinatorTests: XCTestCase {

    private let groupId = UUID()
    private let eventId = UUID()
    private let me = UUID()

    /// Build a coordinator with seeded mock repos. `members` is the full
    /// directory (includes `me`); the coordinator's loadMembers filters.
    private func make(
        members: [MemberWithProfile] = [],
        seedFines: [Fine] = []
    ) -> (AddManualFineCoordinator, MockFineRepository, StubGroupsRepository) {
        let fines = MockFineRepository(seed: seedFines)
        let groups = StubGroupsRepository(membersByGroup: [groupId: members])
        let coord = AddManualFineCoordinator(
            groupId: groupId,
            eventId: eventId,
            fineRepo: fines,
            groupsRepo: groups
        )
        return (coord, fines, groups)
    }

    // MARK: - loadMembers

    func testLoadMembers_excludesCurrentUser() async {
        let other = MemberWithProfile.mock(userId: UUID(), displayName: "Bruno")
        let mine  = MemberWithProfile.mock(userId: me, displayName: "Yo")
        let (c, _, _) = make(members: [mine, other])
        await c.loadMembers(currentUserId: me)
        XCTAssertEqual(c.members.count, 1)
        XCTAssertEqual(c.members.first?.member.userId, other.member.userId)
    }

    func testLoadMembers_sortsFoundersFirst() async {
        let alice  = MemberWithProfile.mock(userId: UUID(), displayName: "Alice", isFounder: false)
        let bob    = MemberWithProfile.mock(userId: UUID(), displayName: "Bob",   isFounder: false)
        let zara   = MemberWithProfile.mock(userId: UUID(), displayName: "Zara",  isFounder: true)
        let (c, _, _) = make(members: [alice, bob, zara])
        await c.loadMembers(currentUserId: me)
        XCTAssertEqual(c.members.map(\.displayName), ["Zara", "Alice", "Bob"])
    }

    // MARK: - canSubmit

    func testCanSubmit_falseWhenNoMember() {
        let (c, _, _) = make()
        c.amountText = "200"
        c.reason = "Llegó tarde"
        XCTAssertFalse(c.canSubmit)
    }

    func testCanSubmit_falseWhenAmountUnparseable() {
        let (c, _, _) = make()
        c.selectedMemberId = UUID()
        c.amountText = "abc"
        c.reason = "Llegó tarde"
        XCTAssertFalse(c.canSubmit)
    }

    func testCanSubmit_falseWhenAmountNegative() {
        let (c, _, _) = make()
        c.selectedMemberId = UUID()
        c.amountText = "-50"
        c.reason = "Llegó tarde"
        XCTAssertFalse(c.canSubmit)
    }

    func testCanSubmit_falseWhenReasonTooShort() {
        let (c, _, _) = make()
        c.selectedMemberId = UUID()
        c.amountText = "200"
        c.reason = " a "
        XCTAssertFalse(c.canSubmit)
    }

    func testCanSubmit_trueWhenAllValid() {
        let (c, _, _) = make()
        c.selectedMemberId = UUID()
        c.amountText = "200"
        c.reason = "Llegó tarde"
        XCTAssertTrue(c.canSubmit)
    }

    // MARK: - submit

    func testSubmit_callsRepoWithCorrectParams() async {
        let target = UUID()
        let (c, fines, _) = make()
        c.selectedMemberId = target
        c.amountText = "200"
        c.reason = "  Llegó tarde  "
        let result = await c.submit()
        XCTAssertNotNil(result)
        let stored = await fines.fines
        XCTAssertEqual(stored.count, 1)
        let f = stored[0]
        XCTAssertEqual(f.groupId, c.groupId)
        XCTAssertEqual(f.userId, target)
        XCTAssertEqual(f.amount, Decimal(string: "200"))
        XCTAssertEqual(f.reason, "Llegó tarde")
        XCTAssertEqual(f.eventId, c.eventId)
        XCTAssertEqual(f.status, .officialized)
        XCTAssertFalse(f.autoGenerated)
    }

    func testSubmit_setsErrorOnRepoFailure() async {
        let (c, fines, _) = make()
        await fines.setThrowOnIssueManual(true)
        c.selectedMemberId = UUID()
        c.amountText = "200"
        c.reason = "Llegó tarde"
        let result = await c.submit()
        XCTAssertNil(result)
        XCTAssertNotNil(c.error)
        XCTAssertFalse(c.isSubmitting)
        XCTAssertEqual(c.amountText, "200")
        XCTAssertEqual(c.reason, "Llegó tarde")
    }

    func testSubmit_clearsErrorOnRetry() async {
        let (c, fines, _) = make()
        await fines.setThrowOnIssueManual(true)
        c.selectedMemberId = UUID()
        c.amountText = "200"
        c.reason = "Llegó tarde"
        _ = await c.submit()
        XCTAssertNotNil(c.error)
        await fines.setThrowOnIssueManual(false)
        let result = await c.submit()
        XCTAssertNotNil(result)
        XCTAssertNil(c.error)
    }

    func testSubmit_returnsNilWhenCantSubmit() async {
        let (c, fines, _) = make()
        let result = await c.submit()
        XCTAssertNil(result)
        let stored = await fines.fines
        XCTAssertTrue(stored.isEmpty)
    }
}

// MARK: - Test fixtures

extension MemberWithProfile {
    static func mock(userId: UUID, displayName: String, isFounder: Bool = false) -> MemberWithProfile {
        let m = Member(
            id: UUID(),
            groupId: UUID(),
            userId: userId,
            displayNameOverride: displayName,
            role: isFounder ? "admin" : "member",
            roles: isFounder ? [.founder, .member] : [.member],
            active: true,
            joinedAt: .now
        )
        return MemberWithProfile(member: m, profile: nil)
    }
}

/// Stub GroupsRepository covering the one method AddManualFineCoordinator
/// touches. Seeded with `[UUID: [MemberWithProfile]]` so tests can specify
/// exact displayName and isFounder values (MockGroupsRepository wraps
/// `[Member]` and would return stub profiles, losing displayName control).
actor StubGroupsRepository: GroupsRepository {
    var membersByGroup: [UUID: [MemberWithProfile]]

    init(membersByGroup: [UUID: [MemberWithProfile]] = [:]) {
        self.membersByGroup = membersByGroup
    }

    func membersWithProfiles(of groupId: UUID) async throws -> [MemberWithProfile] {
        return membersByGroup[groupId] ?? []
    }

    // MARK: - Unused stubs (protocol conformance)

    func listMine() async throws -> [Group] {
        fatalError("not used in AddManualFineCoordinatorTests")
    }

    func get(_ id: UUID) async throws -> GroupDetail {
        fatalError("not used in AddManualFineCoordinatorTests")
    }

    func create(_ params: CreateGroupParams) async throws -> Group {
        fatalError("not used in AddManualFineCoordinatorTests")
    }

    func joinByCode(_ code: String) async throws -> Group {
        fatalError("not used in AddManualFineCoordinatorTests")
    }

    func leave(_ id: UUID) async throws {
        fatalError("not used in AddManualFineCoordinatorTests")
    }

    func members(of groupId: UUID) async throws -> [Member] {
        fatalError("not used in AddManualFineCoordinatorTests")
    }

    func createInitial(_ draft: GroupDraft) async throws -> Group {
        fatalError("not used in AddManualFineCoordinatorTests")
    }

    func updateConfig(groupId: UUID, patch: GroupConfigPatch) async throws -> Group {
        fatalError("not used in AddManualFineCoordinatorTests")
    }

    func updateGovernance(groupId: UUID, rules: GovernanceRules) async throws -> Group {
        fatalError("not used in AddManualFineCoordinatorTests")
    }

    func fetchPreview(byInviteCode code: String) async throws -> InvitePreview {
        fatalError("not used in AddManualFineCoordinatorTests")
    }
}
