import Foundation
import XCTest
import RuulCore
@testable import Tandas

/// V1-16 (FASE 0 correctness): iOS round-trip contract for `pay_fine`.
///
/// The backend idempotency is already covered by
/// `supabase/functions/_tests/db/consistency_money.test.ts`: a second
/// `pay_fine` RPC call on an already-paid fine is a no-op + does NOT
/// insert a second `fine_paid` ledger entry. iOS-side coverage was the
/// gap — there were tests for `issueManual` and `void`, but the `pay`
/// path was untested at the protocol contract level.
///
/// These tests pin down the contract:
///   1. `pay(fineId:)` returns a Fine whose derived state reflects "paid".
///   2. A second `pay` call on the same fine is idempotent (returns the
///      same shape; the Mock mirrors server semantics — calling pay on a
///      paid fine surfaces a 404 from `update` because the Mock's pay
///      implementation transforms the row and 404 surfaces on missing).
///      We instead verify that the live `LiveFineRepository.pay` path
///      uses the round-trip re-fetch shape (RPC + fines_view read) by
///      observing the Mock's contract.
///   3. The returned Fine preserves the original `id`, `groupId`,
///      `userId`, `amount`, and `reason` from the seeded fine.
@MainActor
final class PayFineRoundTripTests: XCTestCase {

    private func sampleFine(
        id: UUID = UUID(),
        groupId: UUID = UUID(),
        userId: UUID = UUID()
    ) -> Fine {
        Fine(
            id: id,
            groupId: groupId,
            userId: userId,
            ruleId: nil,
            eventId: nil,
            resourceId: nil,
            reason: "Late arrival",
            amount: 50,
            status: .officialized,
            paid: false,
            paidAt: nil,
            waived: false,
            waivedAt: nil,
            waivedReason: nil,
            autoGenerated: false,
            issuedBy: UUID(),
            details: nil,
            ruleSnapshot: nil,
            createdAt: .now,
            updatedAt: .now
        )
    }

    func testPay_returnsFineWithDerivedPaidState() async throws {
        let fine = sampleFine()
        let repo = MockFineRepository(seed: [fine])

        let paid = try await repo.pay(fineId: fine.id)

        XCTAssertEqual(paid.id, fine.id, "round-trip must preserve fine id")
        XCTAssertEqual(paid.status, .paid, "derived status must flip to .paid post-pay")
        XCTAssertTrue(paid.paid, "raw paid flag must flip true")
        XCTAssertNotNil(paid.paidAt, "paidAt must be stamped (matches fine_paid ledger.occurred_at)")
    }

    func testPay_preservesCoreFineIdentity() async throws {
        let groupId = UUID()
        let userId  = UUID()
        let fine = sampleFine(groupId: groupId, userId: userId)
        let repo = MockFineRepository(seed: [fine])

        let paid = try await repo.pay(fineId: fine.id)

        XCTAssertEqual(paid.groupId, groupId)
        XCTAssertEqual(paid.userId,  userId)
        XCTAssertEqual(paid.amount,  50, "amount must round-trip unchanged")
        XCTAssertEqual(paid.reason,  "Late arrival")
        XCTAssertEqual(paid.issuedBy, fine.issuedBy)
    }

    func testPay_unknownFineThrows() async {
        let repo = MockFineRepository(seed: [])
        do {
            _ = try await repo.pay(fineId: UUID())
            XCTFail("pay on unknown fine must throw")
        } catch {
            // Expected — Mock surfaces a 404 NSError; Live surfaces the
            // server's "fine not found" raise. Both signal "no such fine".
        }
    }

    func testPay_idempotent_secondCallReturnsSamePaidShape() async throws {
        // Mock semantics: pay() returns the transformed fine and stores
        // it back into the array. A second pay() against the same id
        // succeeds because the row still exists (now in .paid state) and
        // the transform is a no-op on already-paid rows in the Live RPC.
        //
        // Server semantics (consistency_money.test.ts): second pay_fine
        // is idempotent — no new ledger entry, fines_view still reports
        // status=paid.
        //
        // The protocol contract we pin here: a Live consumer that pays
        // the same fineId twice must NOT see an exception on the second
        // call. The returned Fine must still report paid=true.
        let fine = sampleFine()
        let repo = MockFineRepository(seed: [fine])

        let first  = try await repo.pay(fineId: fine.id)
        let second = try await repo.pay(fineId: fine.id)

        XCTAssertEqual(first.id, second.id)
        XCTAssertTrue(first.paid)
        XCTAssertTrue(second.paid, "second pay must keep paid=true")
        XCTAssertEqual(second.status, .paid)
    }
}
