import Foundation
import XCTest
import RuulUI
import RuulCore
@testable import Tandas

@MainActor
final class VoidFineCoordinatorTests: XCTestCase {

    // MARK: - Fixtures

    private func makeFine(
        id: UUID = UUID(),
        groupId: UUID = UUID(),
        userId: UUID = UUID(),
        amount: Decimal = 200,
        reason: String = "Llegó tarde sin avisar",
        status: FineStatus = .officialized
    ) -> Fine {
        Fine(
            id: id, groupId: groupId, userId: userId, ruleId: nil,
            eventId: nil, reason: reason, amount: amount,
            status: status, paid: false, paidAt: nil,
            waived: false, waivedAt: nil, waivedReason: nil,
            autoGenerated: false, issuedBy: UUID(),
            details: nil, ruleSnapshot: nil,
            createdAt: .now, updatedAt: .now
        )
    }

    private func makeMember(userId: UUID, groupId: UUID, displayName: String) -> MemberWithProfile {
        MemberWithProfile(
            member: Member(
                id: UUID(), groupId: groupId, userId: userId,
                role: "member", roles: [.member], joinedAt: .now
            ),
            profile: Profile(id: userId, displayName: displayName, avatarUrl: nil, phone: nil)
        )
    }

    private func makeMockGroupsRepo(seed: [MemberWithProfile]) -> MockGroupsRepository {
        MockGroupsRepository(membersWithProfilesSeed: seed)
    }

    // MARK: - resolveTargetName

    func test_resolveTargetName_setsNameFromGroup() async {
        let fine = makeFine()
        let target = makeMember(userId: fine.userId, groupId: fine.groupId, displayName: "Ana López")
        let coord = VoidFineCoordinator(
            fine: fine,
            fineRepo: MockFineRepository(seed: [fine]),
            groupsRepo: makeMockGroupsRepo(seed: [target])
        )

        await coord.resolveTargetName()

        XCTAssertEqual(coord.targetMemberName, "Ana López")
    }

    func test_resolveTargetName_fallsBackOnLookupFailure() async {
        let fine = makeFine()
        let coord = VoidFineCoordinator(
            fine: fine,
            fineRepo: MockFineRepository(seed: [fine]),
            groupsRepo: makeMockGroupsRepo(seed: [])  // empty — userId not present
        )

        await coord.resolveTargetName()

        XCTAssertEqual(coord.targetMemberName, "el multado")
    }

    // MARK: - canSubmit

    func test_canSubmit_falseWhenReasonEmpty() {
        let fine = makeFine()
        let coord = VoidFineCoordinator(
            fine: fine,
            fineRepo: MockFineRepository(seed: [fine]),
            groupsRepo: makeMockGroupsRepo(seed: [])
        )
        coord.reason = ""

        XCTAssertFalse(coord.canSubmit)
    }

    func test_canSubmit_falseWhenReasonTooShort() {
        let fine = makeFine()
        let coord = VoidFineCoordinator(
            fine: fine,
            fineRepo: MockFineRepository(seed: [fine]),
            groupsRepo: makeMockGroupsRepo(seed: [])
        )
        coord.reason = " a "  // trimmed = "a", count == 1

        XCTAssertFalse(coord.canSubmit)
    }

    func test_canSubmit_trueWhenReasonValid() {
        let fine = makeFine()
        let coord = VoidFineCoordinator(
            fine: fine,
            fineRepo: MockFineRepository(seed: [fine]),
            groupsRepo: makeMockGroupsRepo(seed: [])
        )
        coord.reason = "Duplicada"

        XCTAssertTrue(coord.canSubmit)
    }

    // MARK: - submit

    func test_submit_callsRepoWithCorrectParamsAndReturnsVoidedFine() async {
        let fine = makeFine()
        let repo = MockFineRepository(seed: [fine])
        let coord = VoidFineCoordinator(
            fine: fine,
            fineRepo: repo,
            groupsRepo: makeMockGroupsRepo(seed: [])
        )
        coord.reason = "  Duplicada  "  // exercise trim

        let result = await coord.submit()

        XCTAssertNotNil(result)
        XCTAssertEqual(result?.status, .voided)
        XCTAssertEqual(result?.waivedReason, "Duplicada")
        XCTAssertTrue(result?.waived ?? false)
    }

    func test_submit_setsErrorOnRepoFailure() async {
        let fine = makeFine()
        let repo = MockFineRepository(seed: [fine])
        await repo.setThrowOnVoid(true)
        let coord = VoidFineCoordinator(
            fine: fine,
            fineRepo: repo,
            groupsRepo: makeMockGroupsRepo(seed: [])
        )
        coord.reason = "Duplicada"

        let result = await coord.submit()

        XCTAssertNil(result)
        XCTAssertNotNil(coord.error)
        XCTAssertTrue(coord.error?.contains("admin") ?? false)
    }

    func test_submit_clearsErrorOnRetry() async {
        let fine = makeFine()
        let repo = MockFineRepository(seed: [fine])
        await repo.setThrowOnVoid(true)
        let coord = VoidFineCoordinator(
            fine: fine,
            fineRepo: repo,
            groupsRepo: makeMockGroupsRepo(seed: [])
        )
        coord.reason = "Duplicada"

        // First call fails, sets error.
        _ = await coord.submit()
        XCTAssertNotNil(coord.error)

        // Second call succeeds (throwOnVoid auto-resets after first throw).
        let result = await coord.submit()
        XCTAssertNotNil(result)
        XCTAssertNil(coord.error)
    }

    func test_submit_humanizesStatusGate() async {
        let fine = makeFine(status: .paid)
        let repo = MockFineRepository(seed: [fine])
        await repo.setThrowOnVoid(true)
        await repo.setVoidErrorMessage("cannot void fine with status paid")
        let coord = VoidFineCoordinator(
            fine: fine,
            fineRepo: repo,
            groupsRepo: makeMockGroupsRepo(seed: [])
        )
        coord.reason = "Duplicada"

        _ = await coord.submit()

        XCTAssertNotNil(coord.error)
        XCTAssertTrue(coord.error?.contains("ya no se puede anular") ?? false)
    }

    func test_submit_blocksDoubleTap() async {
        let fine = makeFine()
        let repo = MockFineRepository(seed: [fine])
        let coord = VoidFineCoordinator(
            fine: fine,
            fineRepo: repo,
            groupsRepo: makeMockGroupsRepo(seed: [])
        )
        coord.reason = "Duplicada"

        // Fire two submits concurrently. First wins; second sees isSubmitting
        // and short-circuits via canSubmit.
        async let a = coord.submit()
        async let b = coord.submit()
        let (r1, r2) = await (a, b)

        // At least one should succeed; the second should return nil from the
        // canSubmit guard. Order is non-deterministic but exactly one fine
        // should exist with status .voided.
        XCTAssertTrue(r1 != nil || r2 != nil)
        XCTAssertFalse(r1 != nil && r2 != nil, "expected exactly one submit to win")
    }

    // MARK: - onSubmitted hook

    func test_submit_invokesOnSubmittedOnSuccess() async {
        let fine = makeFine()
        let repo = MockFineRepository(seed: [fine])

        actor Counter {
            var count = 0
            func inc() { count += 1 }
            func value() -> Int { count }
        }
        let counter = Counter()

        let coord = VoidFineCoordinator(
            fine: fine,
            fineRepo: repo,
            groupsRepo: makeMockGroupsRepo(seed: []),
            onSubmitted: { await counter.inc() }
        )
        coord.reason = "Duplicada"

        let result = await coord.submit()

        XCTAssertNotNil(result, "submit should succeed")
        let final = await counter.value()
        XCTAssertEqual(final, 1, "onSubmitted must run exactly once on success")
    }

    func test_submit_doesNotInvokeOnSubmittedOnFailure() async {
        let fine = makeFine()
        let repo = MockFineRepository(seed: [fine])
        await repo.setThrowOnVoid(true)

        actor Counter {
            var count = 0
            func inc() { count += 1 }
            func value() -> Int { count }
        }
        let counter = Counter()

        let coord = VoidFineCoordinator(
            fine: fine,
            fineRepo: repo,
            groupsRepo: makeMockGroupsRepo(seed: []),
            onSubmitted: { await counter.inc() }
        )
        coord.reason = "Duplicada"

        let result = await coord.submit()

        XCTAssertNil(result, "submit should fail")
        let final = await counter.value()
        XCTAssertEqual(final, 0, "onSubmitted must not run when submit fails")
    }
}
