// AUTOGENERATED. Do not edit. Source: scripts/codegen/test/fixtures/sample-input.swift
// Run: make gen

export const sampleTypeValues = [
  "alpha",
  "beta",
  "gammaRay",
] as const;

export type SampleType = (typeof sampleTypeValues)[number];

export function isSampleType(value: string): value is SampleType {
  return (sampleTypeValues as readonly string[]).includes(value);
}
