// AUTOGENERATED. Do not edit. Source: scripts/codegen/test/fixtures/sample-input.swift
// Run: make gen

import Foundation

extension SampleType {
    public static let knownCases: [SampleType] = [
        .alpha,
        .beta,
        .gammaRay,
    ]

    public static let knownRawValues: Set<String> = [
        "alpha",
        "beta",
        "gammaRay",
    ]

    public init(from decoder: Decoder) throws {
        let raw = try decoder.singleValueContainer().decode(String.self)
        self = Self.from(raw: raw)
    }

    public func encode(to encoder: Encoder) throws {
        var c = encoder.singleValueContainer()
        try c.encode(self.rawString)
    }

    public var rawString: String {
        switch self {
        case .alpha: return "alpha"
        case .beta: return "beta"
        case .gammaRay: return "gammaRay"
        case .unknown(let s): return s
        }
    }

    public static func from(raw: String) -> SampleType {
        switch raw {
        case "alpha": return .alpha
        case "beta": return .beta
        case "gammaRay": return .gammaRay
        default: return .unknown(raw)
        }
    }
}
