import type { EnumDecl } from "./parser.ts";

export function emitTs(decl: EnumDecl): string {
  const { typeName, cases, sourceRelative } = decl;
  const valuesIdent = lowerFirst(typeName) + "Values";
  const guardIdent = "is" + typeName;

  const valueLines = cases.map((c) => `  "${c}",`).join("\n");

  return `// AUTOGENERATED. Do not edit. Source: ${sourceRelative}
// Run: make gen

export const ${valuesIdent} = [
${valueLines}
] as const;

export type ${typeName} = (typeof ${valuesIdent})[number];

export function ${guardIdent}(value: string): value is ${typeName} {
  return (${valuesIdent} as readonly string[]).includes(value);
}
`;
}

function lowerFirst(s: string): string {
  return s.length === 0 ? s : s[0].toLowerCase() + s.slice(1);
}
