import type { EnumDecl } from "./parser.ts";

export function emitSwift(decl: EnumDecl): string {
  const { typeName, cases, sourceRelative } = decl;

  const knownCases = cases.map((c) => `        .${c},`).join("\n");
  const knownRaw = cases.map((c) => `        "${c}",`).join("\n");
  const rawStringArms = cases
    .map((c) => `        case .${c}: return "${c}"`)
    .join("\n");
  const fromRawArms = cases
    .map((c) => `        case "${c}": return .${c}`)
    .join("\n");

  return `// AUTOGENERATED. Do not edit. Source: ${sourceRelative}
// Run: make gen

import Foundation

extension ${typeName} {
    public static let knownCases: [${typeName}] = [
${knownCases}
    ]

    public static let knownRawValues: Set<String> = [
${knownRaw}
    ]

    public init(from decoder: Decoder) throws {
        let raw = try decoder.singleValueContainer().decode(String.self)
        self = Self.from(raw: raw)
    }

    public func encode(to encoder: Encoder) throws {
        var c = encoder.singleValueContainer()
        try c.encode(self.rawString)
    }

    public var rawString: String {
        switch self {
${rawStringArms}
        case .unknown(let s): return s
        }
    }

    public static func from(raw: String) -> ${typeName} {
        switch raw {
${fromRawArms}
        default: return .unknown(raw)
        }
    }
}
`;
}
